'use client';
import {useEffect,useMemo,useState} from 'react';
import {Sidebar,Topbar} from '../components';

const items=[['Erasmus+','أوروبا','دراسة وتبادل','تمويل يختلف حسب البرنامج','https://erasmus-plus.ec.europa.eu/'],['DAAD','ألمانيا','دراسات عليا وبحث','منح متعددة وشروط منفصلة','https://www.daad.de/en/studying-in-germany/scholarships/'],['Chevening','المملكة المتحدة','ماجستير','تمويل كامل للمرشحين المؤهلين','https://www.chevening.org/'],['Fulbright','الولايات المتحدة','دراسات عليا وتبادل','حسب برنامج ودولة المتقدم','https://fulbrightprogram.org/']];

export default function Scholarships(){
 const [level,setLevel]=useState('الكل'),[nationality,setNationality]=useState('الأردن'),[country,setCountry]=useState('الكل'),[query,setQuery]=useState('');
 useEffect(()=>{const q=new URLSearchParams(location.search);setNationality(q.get('country')||'الأردن');setCountry(q.get('mode')?.includes('خارج')?'الكل':q.get('country')||'الكل')},[]);
 const rows=useMemo(()=>items.filter(x=>{const text=`${x[0]} ${x[1]} ${x[2]} ${x[3]}`;const levelOk=level==='الكل'||text.includes(level)||(level==='ماجستير'&&/ماجستير|دراسات عليا|graduate/i.test(text))||(level==='بكالوريوس'&&/تبادل|دراسة/.test(x[2]));const natOk=!nationality||true;return levelOk&&(country==='الكل'||x[1].includes(country))&&(!query||text.toLowerCase().includes(query.toLowerCase()));}),[country,query,level,nationality]);
 const reset=()=>{setLevel('الكل');setNationality('الأردن');setCountry('الكل');setQuery('')};
 return <div className="os-shell phase11-private-shell"><Sidebar active="student-portal"/><main className="os-main"><Topbar/><div className="os-content student-service-page"><header><small>SCHOLARSHIP MATCH</small><h1>ابحث عن منحة موثقة</h1><p>نطابق المرحلة والجنسية والدولة، لكن الموعد والأهلية النهائية تؤخذ من الجهة المانحة.</p></header><section className="directory-filter school-filter"><header><div><small>SCHOLARSHIP FILTERS</small><h2>خصص المنح حسب احتياجك</h2></div><button onClick={reset}>مسح الفلاتر</button></header><div><label>المرحلة<select value={level} onChange={e=>setLevel(e.target.value)}><option>الكل</option><option>بكالوريوس</option><option>ماجستير</option><option>دكتوراه</option></select></label><label>الجنسية<input value={nationality} onChange={e=>setNationality(e.target.value)}/></label><label>دولة الدراسة<input value={country} onChange={e=>setCountry(e.target.value)} placeholder="الكل"/></label><label className="filter-search">اسم المنحة أو المجال<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث في المنح"/></label></div><footer><b>{rows.length} منح مطابقة</b><span>الأهلية النهائية من الجهة المانحة</span></footer></section>{rows.length?<section className="scholarship-grid">{rows.map(x=><article key={x[0]}><small>{x[1]}</small><h2>{x[0]}</h2><p>{x[2]}</p><b>{x[3]}</b><footer><a href={x[4]} target="_blank" rel="noreferrer">المصدر الرسمي ↗</a><a href="/student-requests">افحص أهليتي</a></footer></article>)}</section>:<section className="directory-empty"><span>◇</span><h2>لا توجد منح مطابقة</h2><p>وسّع دولة الدراسة أو امسح عبارة البحث.</p><button onClick={reset}>عرض كل المنح</button></section>}</div></main></div>
}
