import { buildFullLesson, mcq, typeAnswer } from "@/src/lib/jordan-books/content/g1-math-s1/lesson-factory";
import type { UnitRecord } from "@/src/lib/jordan-books/schema/types";

export const UNIT_1: UnitRecord = {
  id: "unit-1",
  order: 1,
  titleAr: "الوحدة الأولى: الجمع",
  titleEn: "Unit 1: Addition",
  descriptionAr:
    "نتعلّم خط الأعداد، والجمع بالقفز، والضعف، والإكمال إلى العشرة، وخصائص الجمع. محتوى Success OS أصلي.",
  verificationNote: "NEEDS VERIFICATION vs NCCD Sem1 page order.",
  semesterAssignment: "1",
  lessons: [
    buildFullLesson({
      id: "u1-l1-number-line",
      order: 1,
      titleAr: "خط الأعداد",
      titleEn: "The Number Line",
      outcomes: [
        "أتعرّف خط الأعداد وأقرأ الأعداد من 0 إلى 10.",
        "أحدد موقع عدد على الخط.",
        "أشرح أن الأعداد تكبر يميناً.",
      ],
      prerequisites: ["العد من 0 إلى 10"],
      vocabulary: [
        { term: "خط الأعداد", definition: "خط مرتّب عليه الأعداد من الأصغر إلى الأكبر." },
        { term: "موقع العدد", definition: "مكان العدد على الخط." },
      ],
      hookAr: "درجات السلم تشبه أعداداً مصطفّة. أين يقع العدد 7؟",
      whyAr: "خط الأعداد أداة للجمع والطرح والمقارنة.",
      materialsAr: "مسطرة أو خيط · بطاقات أعداد",
      keyQuestionAr: "كيف أعرف أي عدد أكبر بالنظر إلى الخط؟",
      definitionAr: "خط الأعداد خط مستقيم عليه علامات متساوية؛ كل علامة عدد متتالٍ.",
      explanationAr:
        "نضع 0 في البداية ثم 1 و2… إلى 10 بمسافات متساوية. يميناً تكبر الأعداد، ويساراً تصغر. لإيجاد عدد نضع إصبعاً على موقعه.",
      altExplanationAr: "تخيّل مواقف حافلة مرقّمة بالترتيب؛ رقم أكبر يعني محطة أبعد يميناً على هذا الخط.",
      diagramAr: "0 — 1 — 2 — 3 — 4 — 5 — 6 — 7 — 8 — 9 — 10",
      exampleProblemAr: "أين يقع 3؟",
      exampleStepsAr: "ابدأ من 0، خطوتان إلى 1 و2، ثم خطوة إلى 3.",
      exampleAnswerAr: "3 بين 2 و4",
      wrongMethodAr: "مسافات غير متساوية أو كتابة الأعداد بعكس اتجاه التزايد.",
      mistakeItems: ["مسافات غير متساوية", "عكس الاتجاه"],
      realLifeAr: "أرقام الطوابق ودرجات السلم.",
      mistakesAr: "عدّ البداية مرتين عند تحديد الموقع.",
      guidedPromptAr: "أي عدد أكبر على الخط؟",
      guidedMcq: mcq("أي أكبر؟", ["2", "7", "4"], 1, "7 إلى يمين 2 و4."),
      independent: [
        typeAnswer("ما العدد بين 4 و6؟", "5", "بين 4 و6 يقع 5.", ["٥"]),
        mcq("التحرك يساراً من 5 إلى 3 يعني العدد:", ["كبر", "صغر", "لم يتغير"], 1, "يساراً تصغر."),
        mcq("أقرب عدد إلى 0 من بين:", ["1", "9", "5"], 0, "1 الأقرب إلى 0."),
      ],
      challenge: typeAnswer("من 2 خطوتان يميناً تصل إلى؟", "4", "2→3→4.", ["٤"]),
      closurePoints: ["الخط مرتّب", "يميناً أكبر", "يساراً أصغر"],
      exitQuestion: mcq("أين الأعداد الأكبر؟", ["يسار", "يمين", "فوق"], 1, "يميناً أكبر."),
    }),
    buildFullLesson({
      id: "u1-l2-add-number-line",
      order: 2,
      titleAr: "الجمع باستعمال خط الأعداد",
      titleEn: "Addition on the Number Line",
      outcomes: [
        "أجمع بالقفز يميناً على الخط.",
        "أبدأ من العدد الأول وأقفز بعدد الثاني.",
        "أقرأ الناتج من موقع النهاية.",
      ],
      prerequisites: ["قراءة خط الأعداد"],
      vocabulary: [
        { term: "الجمع", definition: "ضمّ مجموعتين لمعرفة الكل." },
        { term: "الناتج", definition: "العدد النهائي بعد الجمع." },
      ],
      hookAr: "معك 3 كرات وأخذت 2. كيف تقفز على الخط لتعرف المجموع؟",
      whyAr: "الجمع على الخط يجعل العملية مرئية وملموسة.",
      materialsAr: "خط أعداد · عدّاد",
      keyQuestionAr: "من أين أبدأ القفز: من الأول أم من الناتج؟",
      definitionAr: "للجمع: ابدأ من العدد الأول، اقفز يميناً مرات العدد الثاني، اقرأ الموقع.",
      explanationAr:
        "مثال 3+2: قف عند 3، قفزة إلى 4، قفزة إلى 5. الناتج 5. لا تعدّ نقطة البداية ضمن القفزات.",
      altExplanationAr: "الجمع انضمام: ضع المجموعتين معاً ثم عدّ الكل، والخط يساعد على تتبّع العدّ.",
      diagramAr: "3 →(+1) 4 →(+1) 5",
      formulaAr: "ابدأ من a ثم اقفز b خطوات يميناً",
      formulaTeX: "a + b = \\text{end on number line}",
      exampleProblemAr: "احسب 4 + 3 على الخط.",
      exampleStepsAr: "من 4: إلى 5، ثم 6، ثم 7.",
      exampleAnswerAr: "7",
      wrongMethodAr: "عدّ البداية مرتين أو القفز يساراً.",
      realLifeAr: "خطوات إضافية في الممر.",
      mistakesAr: "خلط اتجاه الجمع مع الطرح.",
      guidedPromptAr: "٣ + ٢ = ؟",
      guidedMcq: mcq("٣ + ٢ = ؟", ["4", "5", "6"], 1, "من 3 قفزتان → 5."),
      independent: [
        typeAnswer("5 + 1 =", "6", "من 5 قفزة واحدة → 6.", ["٦"]),
        typeAnswer("6 + 2 =", "8", "من 6 قفزتان → 8.", ["٨"]),
        mcq("2 + 2 =", ["3", "4", "5"], 1, "ضعف اثنين = 4."),
      ],
      challenge: typeAnswer("4 + 1 =", "5", "من 4 قفزة → 5.", ["٥"]),
      closurePoints: ["ابدأ من الأول", "اقفز يميناً", "اقرأ النهاية"],
      exitQuestion: mcq("1 + 4 =", ["4", "5", "6"], 1, "من 1 أربع قفزات → 5."),
    }),
    buildFullLesson({
      id: "u1-l3-doubles",
      order: 3,
      titleAr: "الجمع باستعمال الضعف",
      titleEn: "Addition Using Doubles",
      outcomes: ["أحفظ حقائق الضعف حتى 5+5", "أستخدم الضعف لمجاميع قريبة"],
      prerequisites: ["الجمع بخط الأعداد"],
      vocabulary: [
        { term: "الضعف", definition: "جمع العدد إلى مثيله مثل 4+4." },
        { term: "قريب من الضعف", definition: "ضعف مع زيادة أو نقصان واحد." },
      ],
      hookAr: "يدان: 5 و5. ما المجموع؟",
      whyAr: "حقائق الضعف تسرّع الحساب الذهني.",
      materialsAr: "بطاقات ضعف",
      keyQuestionAr: "إذا عرفت 4+4، فكيف أحسب 4+5؟",
      definitionAr: "الضعف جمع عددين متساويين.",
      explanationAr: "1+1=2، 2+2=4، 3+3=6، 4+4=8، 5+5=10. للقريب من الضعف: 4+5 = (4+4)+1 = 9.",
      altExplanationAr: "الضعف كمرآة: نفس الكمية مرتين.",
      diagramAr: "1+1=2 · 2+2=4 · 3+3=6 · 4+4=8 · 5+5=10",
      exampleProblemAr: "احسب 4 + 5 باستخدام الضعف.",
      exampleStepsAr: "4+4=8، ثم +1 لأن 5=4+1، الناتج 9.",
      exampleAnswerAr: "9",
      wrongMethodAr: "قول 3+3=7.",
      realLifeAr: "زوجا الجوارب، عجلتا دراجة صغيرة.",
      mistakesAr: "خلط الضعف مع العدد التالي.",
      guidedPromptAr: "٥ + ٥ = ؟",
      guidedMcq: mcq("٥ + ٥ = ؟", ["8", "9", "10"], 2, "ضعف خمسة = عشرة."),
      independent: [
        typeAnswer("2+2=", "4", "ضعف اثنين=4.", ["٤"]),
        typeAnswer("3+3=", "6", "ضعف ثلاثة=6.", ["٦"]),
        mcq("4+4=", ["6", "8", "10"], 1, "ضعف أربعة=8."),
      ],
      challenge: typeAnswer("3+4 (قريب من الضعف)=", "7", "3+3=6 ثم +1=7.", ["٧"]),
      closurePoints: ["احفظ الضعف", "استخدمه للمجاور"],
      exitQuestion: mcq("ضعف 1 =", ["1", "2", "3"], 1, "1+1=2."),
    }),
    buildFullLesson({
      id: "u1-l4-make-ten",
      order: 4,
      titleAr: "الجمع بالإكمال إلى العشرة",
      titleEn: "Making Ten",
      outcomes: ["أحوّل الجمع إلى 10 أولاً", "أستخدم 9+1 و8+2 و7+3"],
      prerequisites: ["حقائق الضعف", "العد حتى 10"],
      vocabulary: [{ term: "الإكمال إلى عشرة", definition: "أخذ جزء من العدد الثاني لإكمال الأول إلى 10." }],
      hookAr: "لماذا يحب الرياضيون العدد 10؟",
      whyAr: "الوصول إلى 10 يسهّل الجمع الأكبر.",
      materialsAr: "إطارات عشرة",
      keyQuestionAr: "كم أحتاج من 8 للوصول إلى 10؟",
      definitionAr: "نستخدم جزءاً من العدد الثاني لنصنع 10، ثم نضيف الباقي.",
      explanationAr: "8+5: نأخذ 2 من 5 لنصنع 10، يتبقى 3، إذن 10+3=13. كذلك 9+4 → 10+3=13.",
      altExplanationAr: "إطار العشرة: املأ الفراغات حتى تكتمل العشرة ثم انظر للباقي.",
      exampleProblemAr: "احسب 9 + 4.",
      exampleStepsAr: "9+1=10، يتبقى 3 من الأربعة، 10+3=13.",
      exampleAnswerAr: "13",
      wrongMethodAr: "نسيان طرح الجزء المستخدم من العدد الثاني.",
      realLifeAr: "إكمال علبة إلى 10 قطع.",
      mistakesAr: "الخلط بين ما أُخذ وما تبقى.",
      guidedPromptAr: "٩ + ١ = ؟",
      guidedMcq: mcq("٩ + ١ = ؟", ["9", "10", "11"], 1, "يكملان العشرة."),
      independent: [
        typeAnswer("8+2=", "10", "ثمانية واثنان = عشرة.", ["١٠"]),
        typeAnswer("7+3=", "10", "سبعة وثلاثة = عشرة.", ["١٠"]),
        mcq("6+4=", ["9", "10", "11"], 1, "ستة وأربعة = عشرة."),
      ],
      challenge: typeAnswer("8+5=", "13", "8+2=10 ويتبقى 3 → 13.", ["١٣"]),
      closurePoints: ["اصنع 10", "أضف الباقي"],
      exitQuestion: typeAnswer("9+1=", "10", "تسعة وواحد = عشرة.", ["١٠"]),
    }),
    buildFullLesson({
      id: "u1-l5-properties",
      order: 5,
      titleAr: "خصائص عملية الجمع",
      titleEn: "Properties of Addition",
      outcomes: ["أطبّق التبديل a+b=b+a", "أعرف أن +0 لا يغيّر العدد"],
      prerequisites: ["الجمع بخط الأعداد"],
      vocabulary: [
        { term: "خاصية التبديل", definition: "تبديل الترتيب لا يغيّر ناتج الجمع." },
        { term: "العنصر المحايد", definition: "0 عند الجمع لا يغيّر الناتج." },
      ],
      hookAr: "هل 2+3 مثل 3+2؟",
      whyAr: "الخصائص تساعد على التحقق والسرعة.",
      materialsAr: "مجموعتا مكعبات بألوان مختلفة",
      keyQuestionAr: "ماذا يحدث عند جمع صفر؟",
      definitionAr: "التبديل: a+b=b+a. المحايد: a+0=a.",
      explanationAr: "بدّل ترتيب المجموعتين؛ العدد الكلي واحد. أضف صفراً فلا يتغير العدد. هذا للجمع لا للطرح.",
      altExplanationAr: "على الخط: 2+6 و6+2 ينتهيان عند 8.",
      formulaAr: "a + b = b + a ، و a + 0 = a",
      formulaTeX: "a+b=b+a,\\quad a+0=a",
      exampleProblemAr: "تحقق أن 2+6 = 6+2.",
      exampleStepsAr: "احسب كلاهما على الخط؛ الناتج 8 و8.",
      exampleAnswerAr: "كلاهما 8",
      wrongMethodAr: "ظنّ أن الترتيب يغيّر ناتج الجمع.",
      realLifeAr: "3 كتب + 2 كتب = 2 + 3 نفس الكومة.",
      mistakesAr: "تطبيق التبديل على الطرح لاحقاً بالخطأ.",
      guidedPromptAr: "هل ٢+٣ = ٣+٢؟",
      guidedMcq: mcq("هل ٢+٣ = ٣+٢؟", ["نعم", "لا", "أحياناً"], 0, "خاصية التبديل."),
      independent: [
        typeAnswer("7+0=", "7", "الصفر محايد.", ["٧"]),
        typeAnswer("0+5=", "5", "صفر زائد خمسة = خمسة.", ["٥"]),
        mcq("المعكوس الجمعي لـ 4+3 هو:", ["3+4", "4-3", "3-4"], 0, "التبديل 3+4."),
      ],
      challenge: mcq("أي صحيح؟", ["4+0=0", "4+0=4", "0+4=0"], 1, "4+0=4."),
      closurePoints: ["التبديل", "صفر محايد", "تحقق بالناتج"],
      exitQuestion: typeAnswer("3+2 و2+3 ناتجهما؟", "5", "كلاهما 5.", ["٥"]),
    }),
  ],
};
