import { buildFullLesson, mcq, typeAnswer } from "@/src/lib/jordan-books/content/g1-math-s1/lesson-factory";
import type { UnitRecord } from "@/src/lib/jordan-books/schema/types";

export const UNIT_3: UnitRecord = {
  id: "unit-3",
  order: 3,
  titleAr: "الوحدة الثالثة: الأعداد ضمن منزلتين",
  titleEn: "Unit 3: Two-Digit Numbers",
  descriptionAr: "نتعلّم العشرات والآحاد وتمثيل الأعداد والقيمة المنزلية.",
  verificationNote: "NEEDS VERIFICATION: confirm Sem1 inclusion/page range on NCCD PDF.",
  semesterAssignment: "1",
  lessons: [
    buildFullLesson({
      id: "u3-l1-tens",
      order: 1,
      titleAr: "العشرات",
      titleEn: "Tens",
      outcomes: [
        "أتعرّف أن العشرة حزمة من 10 آحاد.",
        "أعدّ عشرات: 10، 20، 30…",
        "أميز رمز العشرات.",
      ],
      prerequisites: ["العد حتى 20"],
      vocabulary: [
        { term: "عشرة", definition: "مجموعة من 10 آحاد." },
        { term: "عشرات", definition: "حزم من عشرات." },
      ],
      hookAr: "لماذا نربط 10 أصابع معاً كحزمة؟",
      whyAr: "العشرات أساس كتابة الأعداد الكبيرة.",
      materialsAr: "حزم عشرية",
      keyQuestionAr: "كم عشرة في 20؟",
      definitionAr: "العشرة = 10 آحاد. عشرتان = 20.",
      explanationAr: "نعدّ بالقفز عشرات: 10، 20، 30. كل قفزة حزمة كاملة. لا نخلط عدد الحزم مع عدد الآحاد.",
      altExplanationAr: "علبة فيها 10 أقلام = عشرة واحدة.",
      diagramAr: "[10] [10] = 20",
      exampleProblemAr: "كم عشرة في 30؟",
      exampleStepsAr: "30 = 10+10+10 → ثلاث عشرات.",
      exampleAnswerAr: "3 عشرات",
      wrongMethodAr: "عدّ 30 كـ 3 آحاد فقط.",
      realLifeAr: "حزم أقلام للتوزيع على الصف.",
      mistakesAr: "الخلط بين «ثلاث عشرات» و«ثلاثة».",
      guidedPromptAr: "٢٠ فيها كم عشرة؟",
      guidedMcq: mcq("٢٠ =", ["عشرة واحدة", "عشرتان", "ثلاث عشرات"], 1, "20 = عشرتان."),
      independent: [
        typeAnswer("كم عشرة في 10؟", "1", "عشرة واحدة.", ["١", "واحدة"]),
        typeAnswer("عشرتان =", "20", "عشرتان=20.", ["٢٠"]),
        mcq("40 فيها:", ["3 عشرات", "4 عشرات", "5 عشرات"], 1, "4×10=40."),
      ],
      challenge: typeAnswer("5 عشرات =", "50", "5×10=50.", ["٥٠"]),
      closurePoints: ["العشرة حزمة 10", "نعدّ بالحزم", "الرموز 10،20،30…"],
      exitQuestion: mcq("30 =", ["عشرتان", "ثلاث عشرات", "أربعة"], 1, "ثلاث عشرات."),
    }),
    buildFullLesson({
      id: "u3-l2-ones-tens",
      order: 2,
      titleAr: "الآحاد والعشرات",
      titleEn: "Ones and Tens",
      outcomes: [
        "أفرّق منزلة الآحاد عن منزلة العشرات.",
        "أحلّل عدداً مثل 24 إلى عشرات وآحاد.",
        "أقرأ العدد مع ذكر المنزلتين.",
      ],
      prerequisites: ["مفهوم العشرات"],
      vocabulary: [
        { term: "آحاد", definition: "المنزلة اليمنى: كم واحداً فوق العشرات." },
        { term: "منزلة", definition: "مكان الرقم وقيمته حسب موقعه." },
      ],
      hookAr: "في العدد 24، هل الرقم 2 مثل الرقم 4؟",
      whyAr: "نفس الرمز تتغير قيمته حسب المنزلة.",
      materialsAr: "لوحة منازل",
      keyQuestionAr: "ماذا يعني الرقم 3 في 35؟",
      definitionAr: "في عدد منزلتين: اليسار عشرات واليمين آحاد.",
      explanationAr:
        "24 = 2 عشرات و4 آحاد = 20+4. الرقم في العشرات يساوي قيمته×10. الرقم في الآحاد قيمته كما هو.",
      altExplanationAr: "ارسم حزمتين وأربعة مكعبات منفصلة.",
      diagramAr: "عشرات | آحاد\n  2   |  4   → 24",
      exampleProblemAr: "حلّل 18.",
      exampleStepsAr: "1 عشرة و8 آحاد → 10+8=18.",
      exampleAnswerAr: "1 عشرة و8 آحاد",
      wrongMethodAr: "قراءة 18 كـ 1 و8 دون معنى العشرة.",
      realLifeAr: "عدّ البيض: علبة عشرة + بضع حبات.",
      mistakesAr: "عكس منزلتي العشرات والآحاد عند الكتابة.",
      guidedPromptAr: "في 27 رقم العشرات هو؟",
      guidedMcq: mcq("في 27 العشرات =", ["2", "7", "27"], 0, "اليسار=2 عشرات."),
      independent: [
        typeAnswer("35 = ■ عشرات و5 آحاد", "3", "3 عشرات.", ["٣"]),
        typeAnswer("كم آحاد في 42؟", "2", "الآحاد=2.", ["٢"]),
        mcq("19 =", ["1 عشرة و9 آحاد", "9 عشرات و1 آحاد", "19 عشرات"], 0, "1 عشرة و9."),
      ],
      challenge: typeAnswer("اكتب عدداً من 4 عشرات و6 آحاد", "46", "40+6=46.", ["٤٦"]),
      closurePoints: ["يسار=عشرات", "يمين=آحاد", "القيمة تعتمد على الموقع"],
      exitQuestion: mcq("في 50 الآحاد =", ["5", "0", "50"], 1, "الآحاد صفر."),
    }),
    buildFullLesson({
      id: "u3-l3-represent",
      order: 3,
      titleAr: "تمثيل الأعداد ضمن منزلتين",
      titleEn: "Representing Two-Digit Numbers",
      outcomes: [
        "أمثّل الأعداد بالحزم والمكعبات.",
        "أكتب العدد من تمثيل محسوس.",
        "أقارن تمثيلين لنفس العدد.",
      ],
      prerequisites: ["الآحاد والعشرات"],
      vocabulary: [{ term: "تمثيل", definition: "إظهار العدد بصور أو حزم أو رموز." }],
      hookAr: "هل يمكن إظهار 23 بأكثر من طريقة؟",
      whyAr: "التمثيل يعمّق فهم القيمة لا الحفظ الأصم.",
      materialsAr: "حزم ومكعبات · ورق رسم",
      keyQuestionAr: "كيف أتأكد أن تمثيلي يساوي العدد المكتوب؟",
      definitionAr: "نمثّل العشرات بحزم والآحاد بوحدات منفصلة ثم نكتب الرمز.",
      explanationAr:
        "لـ 23: حزمتان + 3 آحاد. يمكن أيضاً عدّ قفزات على خط إلى 23. كل التمثيلات يجب أن تطابق 20+3.",
      altExplanationAr: "ارسم عشر دوائر مغلقة لكل عشرة ونقاط للآحاد.",
      diagramAr: "[10][10] + ••• = 23",
      exampleProblemAr: "ما العدد الممثَّل بحزمة واحدة و7 آحاد؟",
      exampleStepsAr: "10+7=17.",
      exampleAnswerAr: "17",
      wrongMethodAr: "عدّ الحزمة كواحد فقط دون 10.",
      realLifeAr: "ترتيب أقلام في علب عشرية.",
      mistakesAr: "نسيان كتابة صفر الآحاد كما في 30.",
      guidedPromptAr: "حزمتان + 5 آحاد = ؟",
      guidedMcq: mcq("حزمتان و5 =", ["15", "25", "52"], 1, "20+5=25."),
      independent: [
        typeAnswer("3 حزم و0 آحاد =", "30", "30.", ["٣٠"]),
        typeAnswer("1 حزمة و1 آحاد =", "11", "11.", ["١١"]),
        mcq("تمثيل 40 يحتاج:", ["4 آحاد", "4 عشرات", "14"], 1, "أربع حزم."),
      ],
      challenge: typeAnswer("حزمة + 12 آحاد كيف نعيد التجميع؟", "22", "12 آحاد = 1 عشرة و2 → مع الحزمة تصبح 22.", [
        "٢٢",
      ]),
      closurePoints: ["حزم للعشرات", "وحدات للآحاد", "طابق التمثيل مع الكتابة"],
      exitQuestion: mcq("حزمة و9 =", ["19", "91", "10"], 0, "10+9=19."),
    }),
    buildFullLesson({
      id: "u3-l4-place-value",
      order: 4,
      titleAr: "القيمة المنزلية",
      titleEn: "Place Value",
      outcomes: [
        "أحسب قيمة الرقم حسب منزلته.",
        "أوسع العدد: 45 = 40+5.",
        "أقارن أعداداً باستخدام المنازل.",
      ],
      prerequisites: ["تمثيل الأعداد ضمن منزلتين"],
      vocabulary: [
        { term: "قيمة منزلة", definition: "قيمة الرقم حسب مكانه (آحاد/عشرات)." },
        { term: "صورة موسّعة", definition: "كتابة العدد كمجموع قيم المنازل." },
      ],
      hookAr: "في 55، هل الـ 5 اليسرى مثل اليمنى؟",
      whyAr: "القيمة المنزلية أساس المقارنة والعمليات لاحقاً.",
      materialsAr: "لوحة قيمة منزلة",
      keyQuestionAr: "ما قيمة الرقم 7 في 70 وفي 17؟",
      definitionAr: "قيمة رقم العشرات = الرقم×10، وقيمة رقم الآحاد = الرقم×1.",
      explanationAr:
        "في 45: قيمة 4 هي 40، وقيمة 5 هي 5، والمجموع 45. في 55: الـ5 اليسرى =50 واليمنى=5. نستخدم ذلك للمقارنة: ننظر للعشرات أولاً.",
      altExplanationAr: "الصورة الموسعة: 45=40+5، 70=70+0.",
      formulaAr: "ab (منزلتان) = a×10 + b",
      formulaTeX: "10a + b",
      exampleProblemAr: "ما قيمة الرقم 6 في 62؟",
      exampleStepsAr: "6 في العشرات → 6×10=60.",
      exampleAnswerAr: "60",
      wrongMethodAr: "القول إن قيمة 6 هي 6 دائماً بغض النظر عن المنزلة.",
      realLifeAr: "قراءة أعمار أو أرقام منازل بسيطة.",
      mistakesAr: "مقارنة الآحاد قبل العشرات عند اختلاف العشرات.",
      guidedPromptAr: "قيمة 3 في 30؟",
      guidedMcq: mcq("قيمة 3 في 30 =", ["3", "30", "33"], 1, "3 عشرات =30."),
      independent: [
        typeAnswer("وسّع 28", "20+8", "20+8=28.", ["٢٠+٨", "20 + 8"]),
        typeAnswer("قيمة 4 في 14", "4", "4 آحاد =4.", ["٤"]),
        mcq("أي أكبر؟", ["39", "41", "متساويان"], 1, "41 أكبر لأن عشراته أكثر."),
      ],
      challenge: typeAnswer("قيمة 9 في 90", "90", "9 عشرات=90.", ["٩٠"]),
      closurePoints: ["الموقع يغيّر القيمة", "وسّع العدد", "قارن العشرات أولاً"],
      exitQuestion: mcq("45 =", ["4+5", "40+5", "45+0 فقط كشرح وحيد"], 1, "40+5."),
    }),
  ],
};
