import { buildFullLesson, mcq, typeAnswer } from "@/src/lib/jordan-books/content/g1-math-s1/lesson-factory";
import type { UnitRecord } from "@/src/lib/jordan-books/schema/types";

export const UNIT_2: UnitRecord = {
  id: "unit-2",
  order: 2,
  titleAr: "الوحدة الثانية: الطرح",
  titleEn: "Unit 2: Subtraction",
  descriptionAr: "نتعلّم الطرح بخط الأعداد والضعف وإيجاد عشرة، والعلاقة مع الجمع، والحقائق المترابطة، والعدد المفقود.",
  verificationNote: "NEEDS VERIFICATION vs NCCD Sem1 PDF.",
  semesterAssignment: "1",
  lessons: [
    buildFullLesson({
      id: "u2-l1-sub-number-line",
      order: 1,
      titleAr: "الطرح باستعمال خط الأعداد",
      titleEn: "Subtraction on the Number Line",
      outcomes: [
        "أطرح بالقفز يساراً على خط الأعداد.",
        "أبدأ من العدد الأكبر وأقفز بعدد المطروح.",
        "أقرأ الباقي من موقع النهاية.",
      ],
      prerequisites: ["خط الأعداد", "الجمع بالقفز"],
      vocabulary: [
        { term: "الطرح", definition: "إزالة جزء من مجموعة لمعرفة الباقي." },
        { term: "الباقي", definition: "ما يتبقى بعد الطرح." },
      ],
      hookAr: "معك 5 أقلام وأعطيت 2. كيف تعرف الباقي على الخط؟",
      whyAr: "الطرح يظهر يومياً عند الإنفاق والمشاركة.",
      materialsAr: "خط أعداد",
      keyQuestionAr: "إلى أي اتجاه أقفز عند الطرح؟",
      definitionAr: "للطرح على الخط: ابدأ من العدد الأول واقفز يساراً بعدد المطروح.",
      explanationAr: "5-2: قف عند 5، قفزة إلى 4، قفزة إلى 3. الباقي 3. الاتجاه عكس الجمع.",
      altExplanationAr: "ارسم المجموعة واشطب الكمية المزالة ثم عدّ ما بقي.",
      diagramAr: "5 →(-1) 4 →(-1) 3",
      formulaAr: "ابدأ من a واقفز b يساراً",
      formulaTeX: "a - b = \\text{end left on number line}",
      exampleProblemAr: "احسب 6 - 3.",
      exampleStepsAr: "من 6 إلى 5 إلى 4 إلى 3.",
      exampleAnswerAr: "3",
      wrongMethodAr: "القفز يميناً كالجمع.",
      realLifeAr: "أكلت 2 من 7 قطع بسكويت فيبقى 5.",
      mistakesAr: "عدّ نقطة البداية ضمن القفزات.",
      guidedPromptAr: "٥ - ٢ = ؟",
      guidedMcq: mcq("٥ - ٢ = ؟", ["2", "3", "4"], 1, "من 5 قفزتان يساراً → 3."),
      independent: [
        typeAnswer("4-1=", "3", "من 4 خطوة يساراً → 3.", ["٣"]),
        typeAnswer("7-2=", "5", "من 7 خطوتان → 5.", ["٥"]),
        mcq("3-3=", ["0", "1", "3"], 0, "طرح العدد من نفسه = 0."),
      ],
      challenge: typeAnswer("8-3=", "5", "8→7→6→5.", ["٥"]),
      closurePoints: ["الطرح يساراً", "ابدأ من الأول", "اقرأ الباقي"],
      exitQuestion: mcq("9-1=", ["7", "8", "9"], 1, "من 9 خطوة → 8."),
    }),
    buildFullLesson({
      id: "u2-l2-sub-doubles",
      order: 2,
      titleAr: "الطرح باستعمال الضعف",
      titleEn: "Subtraction Using Doubles",
      outcomes: ["أستخدم حقائق الضعف لعكس الطرح", "أحسب مثل 8-4 و10-5 بسرعة"],
      prerequisites: ["حقائق الضعف في الجمع"],
      vocabulary: [{ term: "عكس الضعف", definition: "إذا كان 4+4=8 فإن 8-4=4." }],
      hookAr: "إذا عرفت أن 5+5=10، فماذا يكون 10-5؟",
      whyAr: "ربط الجمع بالطرح يوفر الوقت.",
      materialsAr: "بطاقات ضعف",
      keyQuestionAr: "كيف يساعدني الضعف في الطرح؟",
      definitionAr: "طرح نصف الضعف يعيد أحد العددين المتساويين.",
      explanationAr: "من 4+4=8 نستنتج 8-4=4. من 5+5=10 نستنتج 10-5=5. نتحقق على الخط.",
      altExplanationAr: "اقسم المجموعة إلى نصفين متساويين.",
      exampleProblemAr: "احسب 6 - 3.",
      exampleStepsAr: "نعرف 3+3=6، إذن 6-3=3.",
      exampleAnswerAr: "3",
      wrongMethodAr: "طرح 3 من 6 والحصول على 2 بنسيان العدّ.",
      realLifeAr: "تقسيم 8 حلويات بالتساوي على طفلين.",
      mistakesAr: "استخدام ضعف خاطئ.",
      guidedPromptAr: "١٠ - ٥ = ؟",
      guidedMcq: mcq("١٠ - ٥ = ؟", ["4", "5", "6"], 1, "عكس ضعف خمسة."),
      independent: [
        typeAnswer("8-4=", "4", "عكس 4+4.", ["٤"]),
        typeAnswer("4-2=", "2", "عكس 2+2.", ["٢"]),
        mcq("2-1=", ["0", "1", "2"], 1, "عكس تقريباً لـ 1+1 في هذا المستوى المبسط مع التحقق."),
      ],
      challenge: typeAnswer("10-5=", "5", "عكس 5+5.", ["٥"]),
      closurePoints: ["الضعف له عكس طرحي", "تحقق دائماً"],
      exitQuestion: mcq("8-4=", ["2", "4", "6"], 1, "8-4=4."),
    }),
    buildFullLesson({
      id: "u2-l3-sub-make-ten",
      order: 3,
      titleAr: "الطرح بإيجاد عشرة",
      titleEn: "Subtraction by Making Ten",
      outcomes: ["أطرح بالهبوط إلى 10 أولاً عند الحاجة", "أفكك المطروح إلى أجزاء"],
      prerequisites: ["الإكمال إلى عشرة", "الطرح على الخط"],
      vocabulary: [{ term: "الهبوط إلى عشرة", definition: "طرح جزء للوصول إلى 10 ثم طرح الباقي." }],
      hookAr: "من 13 كيف أصل إلى 10 بسهولة؟",
      whyAr: "استراتيجية منظمة للطرح عبر العشرة.",
      materialsAr: "إطار عشرة",
      keyQuestionAr: "كم أطرح من 13 للوصول إلى 10؟",
      definitionAr: "نطرح أولاً ما يلزم للوصول إلى 10، ثم نطرح ما تبقى من المطروح.",
      explanationAr: "13-5: من 13 إلى 10 نطرح 3، ويتبقى طرح 2، إذن 10-2=8. تحقق: 8+5=13.",
      altExplanationAr: "استخدم خط الأعداد مع محطة عند 10.",
      exampleProblemAr: "احسب 12 - 4.",
      exampleStepsAr: "12-2=10، ثم 10-2=8.",
      exampleAnswerAr: "8",
      wrongMethodAr: "طرح كل المطروح دفعة دون تتبع الأجزاء.",
      realLifeAr: "إنقاص كمية من 12 قطعة على مرحلتين.",
      mistakesAr: "نسيان الجزء الثاني من الطرح.",
      guidedPromptAr: "١١ - ١ = ؟",
      guidedMcq: mcq("١١ - ١ = ؟", ["9", "10", "11"], 1, "هبوط واحد إلى 10."),
      independent: [
        typeAnswer("10-3=", "7", "من عشرة اطرح ثلاثة.", ["٧"]),
        typeAnswer("12-2=", "10", "اثنتان تنزلان إلى عشرة.", ["١٠"]),
        mcq("13-3=", ["9", "10", "11"], 1, "13-3=10."),
      ],
      challenge: typeAnswer("13-5=", "8", "13-3=10 ثم 10-2=8.", ["٨"]),
      closurePoints: ["اهبط إلى 10", "أكمل الطرح", "تحقق بالجمع"],
      exitQuestion: typeAnswer("12-2=", "10", "12-2=10.", ["١٠"]),
    }),
    buildFullLesson({
      id: "u2-l4-add-sub-relation",
      order: 4,
      titleAr: "العلاقة بين الجمع والطرح",
      titleEn: "Relation Between Addition and Subtraction",
      outcomes: ["أفهم أن الطرح عكس الجمع", "أتحقق من الطرح بالجمع"],
      prerequisites: ["جمع وطرح بسيط"],
      vocabulary: [{ term: "العملية العكسية", definition: "الجمع والطرح يعكس كل منهما الآخر." }],
      hookAr: "إذا 3+4=7، فماذا عن 7-4؟",
      whyAr: "التحقق يمنع الأخطاء.",
      materialsAr: "مكعبات بلونين",
      keyQuestionAr: "كيف أتحقق أن طرحي صحيح؟",
      definitionAr: "إذا كان a+b=c فإن c-b=a و c-a=b.",
      explanationAr: "من 3+4=7 نحصل على 7-4=3 و7-3=4. نعيد تجميع الأجزاء للتحقق.",
      altExplanationAr: "قصة: كان عندي 7، أعطيت 4 فيبقى 3؛ إعادة الأربعة ترجعني إلى 7.",
      exampleProblemAr: "تحقق من 9-5=4.",
      exampleStepsAr: "احسب 4+5؛ إن ساوى 9 فالطرح صحيح.",
      exampleAnswerAr: "صحيح لأن 4+5=9",
      wrongMethodAr: "التحقق بجمع خاطئ للعددين.",
      realLifeAr: "إرجاع أشياء بعد استعارتها.",
      mistakesAr: "عكس أي عدد يُطرح دون تمييز.",
      guidedPromptAr: "من 2+5=7 نستنتج 7-5=؟",
      guidedMcq: mcq("7-5=", ["2", "5", "7"], 0, "عكس الجمع يعطي 2."),
      independent: [
        typeAnswer("إذا 6+3=9 فإن 9-3=", "6", "عكس الجمع.", ["٦"]),
        typeAnswer("إذا 4+4=8 فإن 8-4=", "4", "عكس الضعف.", ["٤"]),
        mcq("للتحقق من 10-7=3 نجمع:", ["10+7", "3+7", "3+10"], 1, "3+7 يجب أن تساوي 10."),
      ],
      challenge: typeAnswer("أكمل: 8-■=3 و ■+3=8", "5", "العدد المفقود 5.", ["٥"]),
      closurePoints: ["الطرح عكس الجمع", "تحقق بالجمع"],
      exitQuestion: mcq("5+2=7 ⇒ 7-2=", ["5", "2", "7"], 0, "7-2=5."),
    }),
    buildFullLesson({
      id: "u2-l5-fact-families",
      order: 5,
      titleAr: "الحقائق المترابطة",
      titleEn: "Related Facts / Fact Families",
      outcomes: ["أبني عائلة حقائق من ثلاثة أعداد", "أكتب جملتي جمع وجملتي طرح"],
      prerequisites: ["العلاقة بين الجمع والطرح"],
      vocabulary: [{ term: "عائلة حقائق", definition: "جمل جمع وطرح مرتبطة بنفس الأعداد." }],
      hookAr: "الأعداد 2 و5 و7 أصدقاء. ما الجمل التي يصنعونها؟",
      whyAr: "عائلات الحقائق تثبّت الطلاقة.",
      materialsAr: "مثلث أعداد",
      keyQuestionAr: "كم جملة يمكن أن أصنع من 3 أعداد مرتبطة؟",
      definitionAr: "عائلة الحقائق عادة جملتان جمع وجملتان طرح لنفس الثلاثة أعداد.",
      explanationAr: "للأعداد 2،5،7: 2+5=7، 5+2=7، 7-2=5، 7-5=2.",
      altExplanationAr: "ضع أكبر عدد في رأس المثلث والآخرين في القاعدة.",
      diagramAr: "  7\n / \\\n2———5",
      exampleProblemAr: "ابنِ عائلة للأعداد 3،4،7.",
      exampleStepsAr: "اكتب 3+4=7 و4+3=7 و7-3=4 و7-4=3.",
      exampleAnswerAr: "أربع جمل مترابطة",
      wrongMethodAr: "خلط عدد خارج العائلة مثل إدخال 5.",
      realLifeAr: "قصص أجزاء وكل.",
      mistakesAr: "نسيان إحدى جمل التبديل.",
      guidedPromptAr: "أي جملة تنتمي لعائلة 1،6،7؟",
      guidedMcq: mcq("من عائلة 1،6،7:", ["1+6=7", "1+7=6", "6-7=1"], 0, "1+6=7 صحيحة."),
      independent: [
        typeAnswer("أكمل عائلة 2،3،5: 5-2=", "3", "5-2=3.", ["٣"]),
        mcq("4+5=9 و9-5=؟", ["4", "5", "9"], 0, "9-5=4."),
        typeAnswer("اكتب ناتج 6+1", "7", "6+1=7 ضمن عائلة 1،6،7.", ["٧"]),
      ],
      challenge: typeAnswer("أكبر عدد في عائلة 3 و5 هو؟", "8", "3+5=8.", ["٨"]),
      closurePoints: ["جزءان وكل", "جمعان وطرحان", "نفس الأعداد"],
      exitQuestion: mcq("عائلة 2،2،4 تتضمن:", ["2+2=4", "4+2=2", "2-4=2"], 0, "2+2=4."),
    }),
    buildFullLesson({
      id: "u2-l6-missing-number",
      order: 6,
      titleAr: "العدد المفقود",
      titleEn: "Missing Number",
      outcomes: ["أجد العدد المفقود في جمل جمع أو طرح", "أختار استراتيجية مناسبة"],
      prerequisites: ["عائلات الحقائق"],
      vocabulary: [{ term: "عدد مفقود", definition: "عدد مجهول في جملة رياضية." }],
      hookAr: "3 + ■ = 8. كيف نكشف السر؟",
      whyAr: "حل المجهول مهارة أساس للجبر لاحقاً.",
      materialsAr: "ميزان أو مكعبات",
      keyQuestionAr: "هل أستخدم الجمع أم الطرح لإيجاد المفقود؟",
      definitionAr: "نبحث عن العدد الذي يجعل الجملة صحيحة.",
      explanationAr:
        "إذا 3+■=8 فإن ■=8-3=5. إذا ■-2=6 فإن ■=6+2=8. نحدد العملية العكسية حسب موقع المفقود.",
      altExplanationAr: "فكّر بالقصة: كان الكل 8، ظهر 3، كم اختفى؟",
      exampleProblemAr: "أوجد ■ في 4+■=9.",
      exampleStepsAr: "■=9-4=5. تحقق: 4+5=9.",
      exampleAnswerAr: "5",
      wrongMethodAr: "جمع العددين الظاهرين بدل طرحهما عندما يكون الناتج معلوماً.",
      realLifeAr: "نحتاج 10 كرات ومعنا 6؛ كم ينقص؟",
      mistakesAr: "وضع المفقود دون تحقق.",
      guidedPromptAr: "٢ + ■ = ٦",
      guidedMcq: mcq("٢ + ■ = ٦ ⇒ ■ =", ["3", "4", "8"], 1, "6-2=4."),
      independent: [
        typeAnswer("■ + 5 = 9", "4", "9-5=4.", ["٤"]),
        typeAnswer("7 - ■ = 3", "4", "7-3=4.", ["٤"]),
        mcq("■ - 1 = 5 ⇒ ■=", ["4", "6", "5"], 1, "5+1=6."),
      ],
      challenge: typeAnswer("■ + ■ = 8 و العددان متساويان", "4", "ضعف 4=8.", ["٤"]),
      closurePoints: ["حدد موقع المفقود", "استخدم العكس", "تحقق"],
      exitQuestion: typeAnswer("1+■=4", "3", "4-1=3.", ["٣"]),
    }),
  ],
};
