'use client';
import {useEffect,useState} from 'react';
import {InnerNav} from '../components';
import {productionStages} from '../data/education-data';

const samples={
  summary:['ملخص تمهيدي','يشرح المفاهيم الأساسية بلغة الطالب، مع الأمثلة والمصطلحات الرئيسية وروابط المتطلبات السابقة.'],
  video:['سيناريو فيديو تعليمي','افتتاحية إنسانية، سؤال محفز، شرح بصري خطوة بخطوة، مثال محلول، توقف للتفكير ثم اختبار قصير.'],
  lesson:['خريطة درس تفاعلي','أهداف تعلم، تشخيص سريع، شرح، مساحة كتابة، تدريب متكيف، تلميحات واختبار إتقان.'],
  quiz:['بنك أسئلة أصلي','أسئلة متنوعة الصعوبة مرتبطة بالمهارات، مع تفسير الخطأ بعد انتهاء المحاولة ومراجعة المعلم.']
};

export default function ContentStudio(){
  const [owner,setOwner]=useState('محتوى مملوك لـSuccess 4 Sure'),[file,setFile]=useState(''),[subject,setSubject]=useState(''),[output,setOutput]=useState('summary'),[protection,setProtection]=useState('مشاهدة آمنة — دون تنزيل'),[started,setStarted]=useState(false),[queue,setQueue]=useState([]);
  useEffect(()=>{setQueue(JSON.parse(localStorage.getItem('success-os-production-queue')||'[]'))},[]);
  const canStart=file&&subject&&owner!=='اختر حالة الحقوق';
  return <div className="os-page"><InnerNav active="studio"/><main className="os-page-content studio-page">
    <header className="studio-hero"><div><span>HUMAN-GUIDED AI CONTENT STUDIO</span><h1>من الملف إلى درس يشبه المعلم الحقيقي</h1><p>ارفع PDF أو PowerPoint أو Word أو صورًا أو فيديو. يجهز النظام المادة، لكن لا ينشر أي شرح أو ملخص قبل فحص الحقوق والمراجعة الأكاديمية.</p></div><div className="studio-ai-core"><i>✦</i><b>AI</b><small>بانتظار المفتاح الآمن</small></div></header>
    <section className="studio-layout"><form className="studio-upload" onSubmit={e=>{e.preventDefault();if(canStart)setStarted(true)}}><small>إنشاء مشروع محتوى</small><h2>بيانات المادة</h2><label>اسم المادة أو المساق<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="مثال: General Chemistry I"/></label><label>الدولة والنظام أو الجامعة<input placeholder="الأردن • الجامعة الأردنية / AP / IGCSE..."/></label><label>حالة الملكية والحقوق<select value={owner} onChange={e=>setOwner(e.target.value)}><option>اختر حالة الحقوق</option><option>محتوى مملوك لـSuccess 4 Sure</option><option>رفع المعلم مع تفويض بالنشر</option><option>محتوى بترخيص مفتوح تم التحقق منه</option><option>مرجع محمي للمراجعة الداخلية فقط</option></select></label><label className="upload-drop"><input type="file" multiple accept=".pdf,.ppt,.pptx,.doc,.docx,.txt,.png,.jpg,.jpeg,.mp4,.mov" onChange={e=>setFile(e.target.files?.[0]?.name||'')}/><span>↥</span><b>{file||'اسحب الملفات أو اخترها'}</b><small>PDF • PPTX • DOCX • Images • Video</small></label><label>المخرج الأول<select value={output} onChange={e=>setOutput(e.target.value)}><option value="summary">ملخص منظم</option><option value="video">سيناريو فيديو</option><option value="lesson">درس تفاعلي</option><option value="quiz">أسئلة وتقييم</option></select></label><label>سياسة الحماية<select value={protection} onChange={e=>setProtection(e.target.value)}><option>مشاهدة آمنة — دون تنزيل</option><option>فيديو محمي — بث وعلامة متحركة</option><option>امتحان — نسخة فردية ووقت محدد</option><option>تنزيل مرخص — نسخة مخصصة</option><option>داخلي — فريق المراجعة فقط</option></select></label><div className="studio-protection"><span>✓</span><div><b>SUCCESS Shield مفعّل</b><small>بصمة SHA-256 • علامة مستخدم • سجل فتح • إمكانية السحب</small></div><a href="/security-center">تفاصيل الحماية</a></div><button disabled={!canStart}>{started?'✓ تم إنشاء طلب الإنتاج والحماية':'ابدأ التحليل الآمن'}</button><p>لن تُرسل الملفات إلى أي نموذج قبل تفعيل المفتاح وقبول سياسة الحقوق.</p></form>
      <div className="studio-preview"><header><div><small>معاينة المخرج</small><h2>{samples[output][0]}</h2></div><span>{started?'جاهز للمراجعة':'معاينة'}</span></header><div className="preview-screen protected"><span>SUCCESS AI</span><h3>{subject||'اسم المادة سيظهر هنا'}</h3><p>{samples[output][1]}</p><em className="dynamic-watermark">SUCCESS 4 SURE • WA-000147 • PREVIEW</em><div><i></i><i></i><i></i><i></i></div></div><section><b>بوابة المراجعة البشرية</b><p>المعلم يراجع الدقة، صانع المحتوى يراجع العرض، والمدير الأكاديمي يعتمد النشر.</p><div><span>معلم المادة</span><span>صانع المحتوى</span><span>المدير الأكاديمي</span></div>{started&&<p className="manifest-ready">✓ جُهّز سجل الملكية والحماية وفق سياسة: {protection}</p>}</section></div></section>
    <section className="production-pipeline"><header><small>مسار الإنتاج</small><h2>واضح للإنسان وقابل للتدقيق</h2></header><div>{productionStages.map(([n,t,p])=><article key={n}><b>{n}</b><h3>{t}</h3><p>{p}</p></article>)}</div></section>
    <section className="protected-production-queue"><header><div><small>PROTECTED PRODUCTION QUEUE</small><h2>طلبات الحصص المسجلة من بوابة الطالب</h2><p>لا تظهر الحصة في المكتبة قبل اكتمال المراجعة الأكاديمية واعتماد الحماية.</p></div><b>{queue.length}</b></header>{queue.length?<div>{queue.map((item,i)=><article key={item.id}><div className="queue-id"><span>⬡</span><small>{item.id}</small></div><div><small>{item.country} • {item.system} • الصف {item.grade}</small><h3>{item.subject}</h3><p>{item.plan}</p></div><aside><b>{item.status}</b><span>✓ داخل المنصة فقط</span><span>✓ دون تنزيل</span><span>✓ علامة مستخدم</span><button onClick={()=>{const next=queue.map((x,n)=>n===i?{...x,status:'قيد المراجعة الأكاديمية'}:x);setQueue(next);localStorage.setItem('success-os-production-queue',JSON.stringify(next))}}>بدء المراجعة</button></aside></article>)}</div>:<div className="queue-empty">لم تصل طلبات بعد. اطلب حصة مسجلة من بوابة الطالب لتظهر هنا.</div>}</section>
  </main></div>
}
