import { USER_ROLES, type UserRole } from "@/types/roles";

export const PERMISSIONS = {
  // Platform
  PLATFORM_MANAGE: "platform:manage",
  PLATFORM_CONFIG: "platform:config",
  PLATFORM_AUDIT: "platform:audit",

  // Users
  USERS_READ: "users:read",
  USERS_WRITE: "users:write",
  USERS_DELETE: "users:delete",
  USERS_SUSPEND: "users:suspend",

  // Roles
  ROLES_READ: "roles:read",
  ROLES_ASSIGN: "roles:assign",
  ROLES_REVOKE: "roles:revoke",

  // Education
  COURSES_CREATE: "courses:create",
  COURSES_READ: "courses:read",
  COURSES_UPDATE: "courses:update",
  COURSES_DELETE: "courses:delete",
  COURSES_PUBLISH: "courses:publish",

  STUDENTS_READ: "students:read",
  STUDENTS_MANAGE: "students:manage",
  STUDENTS_ENROLL: "students:enroll",

  GRADES_READ: "grades:read",
  GRADES_WRITE: "grades:write",

  ACADEMIC_MANAGE: "academic:manage",
  ACADEMIC_REPORTS: "academic:reports",

  INSTITUTION_MANAGE: "institution:manage",
  INSTITUTION_REPORTS: "institution:reports",

  // Employment
  JOBS_CREATE: "jobs:create",
  JOBS_READ: "jobs:read",
  JOBS_UPDATE: "jobs:update",
  JOBS_DELETE: "jobs:delete",
  JOBS_APPLY: "jobs:apply",
  JOBS_MANAGE: "jobs:manage",

  // Content
  CONTENT_CREATE: "content:create",
  CONTENT_READ: "content:read",
  CONTENT_UPDATE: "content:update",
  CONTENT_DELETE: "content:delete",
  CONTENT_PUBLISH: "content:publish",

  SOCIAL_MANAGE: "social:manage",
  SOCIAL_PUBLISH: "social:publish",
  SOCIAL_ANALYTICS: "social:analytics",

  // Support
  SUPPORT_READ: "support:read",
  SUPPORT_RESPOND: "support:respond",
  SUPPORT_MANAGE: "support:manage",
  SUPPORT_ESCALATE: "support:escalate",

  // Dashboard
  DASHBOARD_ACCESS: "dashboard:access",
  ANALYTICS_VIEW: "analytics:view",
  REPORTS_EXPORT: "reports:export",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export type PermissionCheck = {
  permission: Permission;
  granted: boolean;
};

export type RolePermissionMap = Record<UserRole, readonly Permission[]>;

const PLATFORM_FULL: Permission[] = [
  PERMISSIONS.PLATFORM_MANAGE,
  PERMISSIONS.PLATFORM_CONFIG,
  PERMISSIONS.PLATFORM_AUDIT,
  PERMISSIONS.USERS_READ,
  PERMISSIONS.USERS_WRITE,
  PERMISSIONS.USERS_DELETE,
  PERMISSIONS.USERS_SUSPEND,
  PERMISSIONS.ROLES_READ,
  PERMISSIONS.ROLES_ASSIGN,
  PERMISSIONS.ROLES_REVOKE,
  PERMISSIONS.DASHBOARD_ACCESS,
  PERMISSIONS.ANALYTICS_VIEW,
  PERMISSIONS.REPORTS_EXPORT,
];

export const ROLE_PERMISSIONS: RolePermissionMap = {
  [USER_ROLES.SUPER_ADMIN]: [
    ...ALL_PERMISSIONS,
  ],

  [USER_ROLES.OWNER]: [
    ...PLATFORM_FULL,
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.JOBS_READ,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.ACADEMIC_REPORTS,
    PERMISSIONS.INSTITUTION_REPORTS,
  ],

  [USER_ROLES.ADMIN]: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_WRITE,
    PERMISSIONS.USERS_SUSPEND,
    PERMISSIONS.ROLES_READ,
    PERMISSIONS.ROLES_ASSIGN,
    PERMISSIONS.DASHBOARD_ACCESS,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.JOBS_READ,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.SUPPORT_MANAGE,
    PERMISSIONS.REPORTS_EXPORT,
  ],

  [USER_ROLES.ACADEMIC_DIRECTOR]: [
    PERMISSIONS.ACADEMIC_MANAGE,
    PERMISSIONS.ACADEMIC_REPORTS,
    PERMISSIONS.COURSES_CREATE,
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.COURSES_UPDATE,
    PERMISSIONS.COURSES_DELETE,
    PERMISSIONS.COURSES_PUBLISH,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_MANAGE,
    PERMISSIONS.GRADES_READ,
    PERMISSIONS.DASHBOARD_ACCESS,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
  ],

  [USER_ROLES.TEACHER]: [
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.COURSES_UPDATE,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.GRADES_READ,
    PERMISSIONS.GRADES_WRITE,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.DASHBOARD_ACCESS,
    PERMISSIONS.ANALYTICS_VIEW,
  ],

  [USER_ROLES.STUDENT]: [
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.STUDENTS_ENROLL,
    PERMISSIONS.GRADES_READ,
    PERMISSIONS.JOBS_READ,
    PERMISSIONS.JOBS_APPLY,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.DASHBOARD_ACCESS,
  ],

  [USER_ROLES.SCHOOL_STUDENT]: [
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.STUDENTS_ENROLL,
    PERMISSIONS.GRADES_READ,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.DASHBOARD_ACCESS,
  ],

  [USER_ROLES.UNIVERSITY_STUDENT]: [
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.STUDENTS_ENROLL,
    PERMISSIONS.GRADES_READ,
    PERMISSIONS.JOBS_READ,
    PERMISSIONS.JOBS_APPLY,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.DASHBOARD_ACCESS,
  ],

  [USER_ROLES.PARENT]: [
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.GRADES_READ,
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.SUPPORT_RESPOND,
    PERMISSIONS.DASHBOARD_ACCESS,
  ],

  [USER_ROLES.SCHOOL]: [
    PERMISSIONS.INSTITUTION_MANAGE,
    PERMISSIONS.INSTITUTION_REPORTS,
    PERMISSIONS.COURSES_CREATE,
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.COURSES_UPDATE,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_MANAGE,
    PERMISSIONS.JOBS_CREATE,
    PERMISSIONS.JOBS_READ,
    PERMISSIONS.DASHBOARD_ACCESS,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
  ],

  [USER_ROLES.COLLEGE]: [
    PERMISSIONS.INSTITUTION_MANAGE,
    PERMISSIONS.INSTITUTION_REPORTS,
    PERMISSIONS.ACADEMIC_MANAGE,
    PERMISSIONS.COURSES_CREATE,
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.COURSES_UPDATE,
    PERMISSIONS.COURSES_PUBLISH,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_MANAGE,
    PERMISSIONS.DASHBOARD_ACCESS,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
  ],

  [USER_ROLES.UNIVERSITY]: [
    PERMISSIONS.INSTITUTION_MANAGE,
    PERMISSIONS.INSTITUTION_REPORTS,
    PERMISSIONS.ACADEMIC_MANAGE,
    PERMISSIONS.ACADEMIC_REPORTS,
    PERMISSIONS.COURSES_CREATE,
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.COURSES_UPDATE,
    PERMISSIONS.COURSES_PUBLISH,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_MANAGE,
    PERMISSIONS.JOBS_CREATE,
    PERMISSIONS.JOBS_READ,
    PERMISSIONS.DASHBOARD_ACCESS,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
  ],

  [USER_ROLES.EDUCATIONAL_CENTER]: [
    PERMISSIONS.INSTITUTION_MANAGE,
    PERMISSIONS.COURSES_CREATE,
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.COURSES_UPDATE,
    PERMISSIONS.COURSES_PUBLISH,
    PERMISSIONS.STUDENTS_READ,
    PERMISSIONS.STUDENTS_MANAGE,
    PERMISSIONS.DASHBOARD_ACCESS,
    PERMISSIONS.ANALYTICS_VIEW,
  ],

  [USER_ROLES.EMPLOYEE]: [
    PERMISSIONS.DASHBOARD_ACCESS,
    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.CONTENT_READ,
  ],

  [USER_ROLES.EMPLOYER]: [
    PERMISSIONS.JOBS_CREATE,
    PERMISSIONS.JOBS_READ,
    PERMISSIONS.JOBS_UPDATE,
    PERMISSIONS.JOBS_DELETE,
    PERMISSIONS.JOBS_MANAGE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.DASHBOARD_ACCESS,
    PERMISSIONS.ANALYTICS_VIEW,
  ],

  [USER_ROLES.RECRUITMENT_COMPANY]: [
    PERMISSIONS.JOBS_CREATE,
    PERMISSIONS.JOBS_READ,
    PERMISSIONS.JOBS_UPDATE,
    PERMISSIONS.JOBS_MANAGE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.DASHBOARD_ACCESS,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
  ],

  [USER_ROLES.JOB_SEEKER]: [
    PERMISSIONS.JOBS_READ,
    PERMISSIONS.JOBS_APPLY,
    PERMISSIONS.COURSES_READ,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.DASHBOARD_ACCESS,
  ],

  [USER_ROLES.CONTENT_CREATOR]: [
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.CONTENT_UPDATE,
    PERMISSIONS.CONTENT_DELETE,
    PERMISSIONS.CONTENT_PUBLISH,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.DASHBOARD_ACCESS,
  ],

  [USER_ROLES.SOCIAL_MEDIA_MANAGER]: [
    PERMISSIONS.SOCIAL_MANAGE,
    PERMISSIONS.SOCIAL_PUBLISH,
    PERMISSIONS.SOCIAL_ANALYTICS,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.CONTENT_UPDATE,
    PERMISSIONS.CONTENT_PUBLISH,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.DASHBOARD_ACCESS,
  ],

  [USER_ROLES.CUSTOMER_SUPPORT]: [
    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.SUPPORT_RESPOND,
    PERMISSIONS.SUPPORT_MANAGE,
    PERMISSIONS.SUPPORT_ESCALATE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.DASHBOARD_ACCESS,
  ],
};

export function getPermissionsForRole(role: UserRole): readonly Permission[] {
  return ROLE_PERMISSIONS[role];
}

export function roleHasPermission(
  role: UserRole,
  permission: Permission,
): boolean {
  return ROLE_PERMISSIONS[role].includes(permission);
}

export function canAccessRoleDashboard(
  userRole: UserRole,
  targetRole: UserRole,
): boolean {
  if (userRole === targetRole) return true;

  const elevatedRoles: UserRole[] = [
    USER_ROLES.SUPER_ADMIN,
    USER_ROLES.OWNER,
    USER_ROLES.ADMIN,
  ];

  if (elevatedRoles.includes(userRole)) return true;

  return false;
}
