const base=()=>String(process.env.SUCCESS_OS_ASSET_STORE_URL||'').replace(/\/$/,'');
const headers=()=>({'Content-Type':'application/json',Authorization:`Bearer ${process.env.SUCCESS_OS_ASSET_STORE_TOKEN||''}`});
export function assetStoreConfigured(){return Boolean(base()&&process.env.SUCCESS_OS_ASSET_STORE_TOKEN)}
export async function loadLessonPackage(fingerprint){if(!assetStoreConfigured())return null;const r=await fetch(`${base()}/lesson-packages/${encodeURIComponent(fingerprint)}`,{headers:headers()});if(r.status===404)return null;if(!r.ok)throw new Error(`ASSET_STORE_READ_${r.status}`);return r.json()}
export async function saveLessonPackage(fingerprint,data){if(!assetStoreConfigured())return {stored:false,reason:'ASSET_STORE_NOT_CONFIGURED'};const r=await fetch(`${base()}/lesson-packages/${encodeURIComponent(fingerprint)}`,{method:'PUT',headers:headers(),body:JSON.stringify(data)});if(!r.ok)throw new Error(`ASSET_STORE_WRITE_${r.status}`);return {stored:true,...await r.json().catch(()=>({}))}}
export async function loadBookPackage(fingerprint){if(!assetStoreConfigured())return null;const r=await fetch(`${base()}/book-packages/${encodeURIComponent(fingerprint)}`,{headers:headers()});if(r.status===404)return null;if(!r.ok)throw new Error(`BOOK_STORE_READ_${r.status}`);return r.json()}
export async function saveBookPackage(fingerprint,data){if(!assetStoreConfigured())return {stored:false,reason:'ASSET_STORE_NOT_CONFIGURED'};const r=await fetch(`${base()}/book-packages/${encodeURIComponent(fingerprint)}`,{method:'PUT',headers:headers(),body:JSON.stringify(data)});if(!r.ok)throw new Error(`BOOK_STORE_WRITE_${r.status}`);return {stored:true,...await r.json().catch(()=>({}))}}
export async function loadKnowledgeDossier(fingerprint){if(!assetStoreConfigured())return null;const r=await fetch(`${base()}/knowledge-dossiers/${encodeURIComponent(fingerprint)}`,{headers:headers()});if(r.status===404)return null;if(!r.ok)throw new Error(`KNOWLEDGE_STORE_READ_${r.status}`);return r.json()}
export async function saveKnowledgeDossier(fingerprint,data){if(!assetStoreConfigured())return {stored:false,reason:'ASSET_STORE_NOT_CONFIGURED'};const r=await fetch(`${base()}/knowledge-dossiers/${encodeURIComponent(fingerprint)}`,{method:'PUT',headers:headers(),body:JSON.stringify(data)});if(!r.ok)throw new Error(`KNOWLEDGE_STORE_WRITE_${r.status}`);return {stored:true,...await r.json().catch(()=>({}))}}
export async function importAsset({sourceUrl,lessonId,type,contentType}){if(!assetStoreConfigured())return {stored:false,reason:'ASSET_STORE_NOT_CONFIGURED'};const r=await fetch(`${base()}/assets/import`,{method:'POST',headers:headers(),body:JSON.stringify({sourceUrl,lessonId,type,contentType})});if(!r.ok)throw new Error(`ASSET_IMPORT_${r.status}`);return {stored:true,...await r.json()}}
export function assetStoreStatus(){return {configured:assetStoreConfigured(),mode:assetStoreConfigured()?'permanent-external-store':'preview-only',required:assetStoreConfigured()?[]:['SUCCESS_OS_ASSET_STORE_URL','SUCCESS_OS_ASSET_STORE_TOKEN']}}
