import {AI_TASKS} from './provider-registry';
import {assetStoreStatus,loadLessonPackage,saveLessonPackage} from './asset-store';
import {generateJSON} from './orchestrator';
import {verifyMasterLessonPackage} from './master-quality-standard';
import {verifyResearchPacket} from './knowledge-acquisition-engine';

const portals=new Set(['student','school','university','teacher','center','ai-teacher','ai-tutor','recorded-course','live-class']);
const required=['portal','curriculumType','curriculum','gradeOrYear','subject','unit','lesson','language'];
const clean=(x,n=180)=>String(x||'').trim().slice(0,n);
const stable=value=>JSON.stringify(value,Object.keys(value).sort());
export async function lessonFingerprint(input){const identity={country:clean(input.country),portal:clean(input.portal),curriculumType:clean(input.curriculumType),curriculum:clean(input.curriculum),authority:clean(input.authority),stage:clean(input.stage),gradeOrYear:clean(input.gradeOrYear),semester:clean(input.semester),subject:clean(input.subject),unit:clean(input.unit),lesson:clean(input.lesson),language:clean(input.language),specVersion:clean(input.specVersion||'2026.07'),sourceHashes:[...(input.sourceHashes||[])].sort()};const bytes=new TextEncoder().encode(stable(identity)),hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function validate(input){const errors={};for(const key of required)if(!clean(input[key]))errors[key]='required';if(input.portal&&!portals.has(input.portal))errors.portal='unsupported portal';if(!['national','international','university','professional'].includes(input.curriculumType))errors.curriculumType='invalid curriculum type';return errors}
function packageQuality(data){const checks={objectives:data.objectives?.length>=3,teacherScript:String(data.teacherScript||'').split(/\s+/).length>=1700,notes:String(data.studentNotes||'').length>=500,segments:data.lessonSegments?.length>=8,flashcards:data.flashcards?.length>=8,practice:data.practiceQuestions?.length>=5,quiz:data.lessonQuiz?.length>=5,homework:data.homework?.length>=3,unitExam:data.unitExam?.length>=5,finalExam:data.finalExam?.length>=5,sources:data.sourceNotes?.length>=1};return {checks,score:Math.round(Object.values(checks).filter(Boolean).length/Object.keys(checks).length*100),passed:Object.values(checks).every(Boolean)}}

export async function buildLessonPackage(input,{force=false}={}){
 const errors=validate(input);if(Object.keys(errors).length)throw Object.assign(new Error('INVALID_LESSON_IDENTITY'),{details:errors});
 const research=verifyResearchPacket(input.researchDossier||{});if(!research.passed)throw Object.assign(new Error('INSUFFICIENT_VERIFIED_RESEARCH'),{details:research});
 const fingerprint=await lessonFingerprint(input),store=assetStoreStatus();
 if(!force&&store.configured){const cached=await loadLessonPackage(fingerprint);if(cached)return {...cached,reused:true,persistence:store}}
 const identity={id:fingerprint,fingerprint,portal:input.portal,country:clean(input.country),curriculumType:input.curriculumType,curriculum:clean(input.curriculum),authority:clean(input.authority),stage:clean(input.stage),gradeOrYear:clean(input.gradeOrYear),semester:clean(input.semester),subject:clean(input.subject),unit:clean(input.unit),lesson:clean(input.lesson),language:clean(input.language),specVersion:clean(input.specVersion||'2026.07'),researchVerified:true,verifiedResearchFacts:research.facts.deduplicated};
 const prompt=`Create an original, academically conservative SUCCESS OS lesson package as JSON. Identity: ${JSON.stringify(identity)}. Align only to the named curriculum and grade; never mix curricula, copy textbooks, reproduce official exam questions, or invent official requirements. The spoken teacherScript must be 1,900–2,600 words for a human-like 15–30 minute recorded class with a hook, objectives, prerequisite check, precise explanation, definitions, equations where relevant, three worked examples, two graph/diagram descriptions, real-world application, common mistakes, guided practice pauses, challenge, recap, and exit questions. Create reusable student assets. Return JSON only with: title,objectives[4],learningOutcomes[4],prerequisites[],teacherScript,lessonSegments[{title,minutes,visualDirection}],slideOutline[{title,content,visualPrompt}],whiteboardPlan[],studentNotes,summary,flashcards[{front,back}],mindMap{center,branches[]},practiceQuestions[{question,type,answer,explanation}],lessonQuiz[{question,options,answer,explanation}],homework[],unitExam[{question,type,answer}],finalExam[{question,type,answer}],simulations[{title,subject,purpose}],sourceNotes[{source,usage}],commonMistakes[],accessibility{captions,transcript,readingMode}. Every question must be original and match the actual assessment style without claiming to be official.`;
 const generated=await generateJSON({task:AI_TASKS.LESSON_WRITING,prompt,effort:'high',maxOutputTokens:9000,safetyIdentifier:'success-os-lesson-engine'}),quality=packageQuality(generated.data);
 const lessonPackage={schema:'success-os.lesson-package.v1',identity,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),content:generated.data,assets:{recordedLesson:{status:'not-produced',minimumMinutes:15,maximumMinutes:30},aiTeacherVideo:{status:'not-produced'},slides:{status:'script-ready'},whiteboard:{status:'script-ready'},images:{status:'prompts-ready'},animations:{status:'prompts-ready'},simulations:{status:'planned'},voice:{status:'not-produced'},subtitles:{status:'not-produced'}},videoFeatures:{adaptiveStreaming:false,resumePosition:false,chapters:false,timestamps:false,bookmarks:false,transcript:false,subtitles:false,multilingualAudio:false,playbackSpeed:false,crossDeviceSync:false,lowBandwidthMode:false},generation:{provider:generated.provider,fallbacks:generated.attempts,quality},approval:{sourceRights:false,scientific:false,curriculum:false,language:false,teacher:false,humanAcademic:false,publishable:false},rights:{originalRewriteRequired:true,sourceLicenseReviewRequired:true,protectedAccess:true},reused:false,persistence:store};
 lessonPackage.masterQuality=verifyMasterLessonPackage(lessonPackage);
 lessonPackage.approval.publishable=lessonPackage.masterQuality.publicationAllowed;
 if(store.configured){const saved=await saveLessonPackage(fingerprint,lessonPackage);lessonPackage.persistence={...store,...saved}}
 return lessonPackage;
}

export function lessonEngineStatus(){return {portals:[...portals],curriculumTypes:['national','international','university','professional'],reuse:'SHA-256 curriculum-and-source fingerprint',researchGate:'verified multi-source dossier required before generation',persistence:assetStoreStatus(),publicationRule:'quality gate + scientific review + curriculum review + teacher approval'}}
