import type { InteractiveLesson, InteractiveQuestion } from "@/src/lib/sos-lesson-engine/schema/types";

function q(partial: InteractiveQuestion): InteractiveQuestion {
  return partial;
}

/**
 * Complete reference interactive lesson:
 * Grade 1 Mathematics — Unit 0 — Lesson 1: Numbers 1, 2, 3
 * Original Success OS content aligned to verified Jordan G1 Math companion outcomes.
 * No AI teacher video. Official PDF link-only.
 */
export const G1_MATH_U0_L1_REFERENCE: InteractiveLesson = {
  id: "sos-il-jo-g1-math-u0-l1-numbers-123",
  schemaVersion: "sos.interactive-lesson.v1",
  identity: {
    country: "Jordan",
    curriculum: "national",
    curriculumVersion: "NEEDS VERIFICATION",
    academicYear: "NEEDS VERIFICATION",
    grade: "1",
    gradeAr: "الصف الأول",
    semester: "1",
    semesterAr: "الفصل الدراسي الأول",
    pathway: "general",
    pathwayAr: "عام",
    subject: "math",
    subjectAr: "الرياضيات",
    bookId: "jo-g1-s1-math-student-book",
    bookTitleAr: "الرياضيات — كتاب تفاعلي Success OS — الفصل الدراسي الأول",
    unitId: "unit-0",
    unitTitleAr: "الوحدة التمهيدية: الأعداد حتى 20",
    lessonId: "u0-l1-numbers-123",
    lessonTitleAr: "الأعداد 1 ، 2 ، 3",
    lessonTitleEn: "Numbers 1, 2, 3",
    officialPageRange: "NEEDS VERIFICATION مقابل طبعة NCCD الحالية",
    learningOutcomes: [
      "أعدّ حتى 3 وأتعرّف الرموز 1 و2 و3.",
      "أربط كل عدد بمجموعة أشياء مناسبة.",
      "أكتب الأعداد 1 و2 و3 بخط واضح.",
    ],
    officialOutcomesNote: "نواتج مرافقة Success OS بمحاذاة منهاج الصف الأول — ليست نصاً حكومياً منسوخاً.",
    skills: ["العدّ", "التمييز البصري", "الكتابة", "المطابقة"],
    prerequisites: ["التمييز بين الأشياء", "القدرة على الإشارة"],
    estimatedMinutes: 25,
    materialsAr: "مكعبات أو أزرار · ورقة · قلم · أصابع اليد",
    sources: [
      {
        name: "NCCD Grade 1 textbooks catalog",
        url: "https://www.nccd.gov.jo/ar/pages/TextBooksGrade/68",
        usage: "official-discovery-link-only",
      },
      {
        name: "Success OS G1 Math Sem1 companion structure",
        url: "/jordan-books/jordan/national/grade-1/semester-1/math/student-book",
        usage: "sos-original-aligned-structure",
      },
    ],
    rightsStatus: "sos_original_aligned",
    editorialStatus: "draft",
    preparedBy: "Prepared by Mr Waseem Allabadi",
  },
  modes: ["student_paced", "teacher_paced", "assignment", "revision_game"],
  hook: {
    openingAr: "مرحباً يا بطل العدّ! اليوم نتعرّف على أصدقاء صغار: 1 و2 و3.",
    questionAr: "كم تفاحة ترى إذا رأيت تفاحة واحدة ثم أضفت أخرى؟",
    situationAr: "في صفّك ثلاثة أقلام على الطاولة. كيف تعدّها دون نسيان؟",
    visualAr: "🍎    🍎🍎    🍎🍎🍎",
    predictionPromptAr: "توقّع: ماذا يأتي بعد العدد 2؟",
    priorConnectionAr: "سبق أن رأيت أشياء كثيرة حولك — اليوم نُسمّي كمياتها الصغيرة بالأعداد.",
  },
  prerequisiteCheck: {
    minCorrect: 2,
    recoveryExplanationAr:
      "قبل العدّ نحتاج أن نميّز الأشياء ونشير إليها واحداً واحداً. جرّب أن تشير بإصبعك إلى كل شكل دون تكرار.",
    questions: [
      q({
        id: "prereq-1",
        promptAr: "أيّ مجموعة فيها أشياء أكثر؟",
        kind: "mcq",
        options: ["●", "● ●", "لا شيء"],
        correctIndex: 1,
        explanationAr: "نقطتان أكثر من نقطة واحدة.",
        hint1Ar: "عدّ النقاط في كل خيار.",
        hint2Ar: "اختر المجموعة التي فيها اثنان.",
        difficulty: "basic",
        masteryWeight: 0.5,
        points: 5,
        skill: "التمييز البصري",
      }),
      q({
        id: "prereq-2",
        promptAr: "هل تستطيع الإشارة إلى شيء واحد فقط؟",
        kind: "true_false",
        options: ["نعم", "لا"],
        correctIndex: 0,
        explanationAr: "الإشارة لشيء واحد مهارة جاهزية للعدّ.",
        hint1Ar: "اختر نعم إذا كنت مستعداً.",
        hint2Ar: "العدّ يبدأ بالإشارة لشيء واحد.",
        difficulty: "basic",
        masteryWeight: 0.5,
        points: 5,
        skill: "العدّ",
      }),
      q({
        id: "prereq-3",
        promptAr: "أيّ صورة تمثّل شيئاً واحداً؟",
        kind: "mcq",
        options: ["⭐⭐", "⭐", "⭐⭐⭐"],
        correctIndex: 1,
        explanationAr: "نجمة واحدة تعني شيئاً واحداً.",
        hint1Ar: "ابحث عن نجمة بمفردها.",
        hint2Ar: "ليس اثنتين ولا ثلاثاً.",
        difficulty: "basic",
        masteryWeight: 0.5,
        points: 5,
        skill: "التمييز البصري",
      }),
    ],
    recoveryActivity: q({
      id: "prereq-recovery",
      promptAr: "أشر بعدّ الأصابع: كم إصبعاً إذا رفعت إصبعاً واحداً؟",
      kind: "mcq",
      options: ["1", "2", "3"],
      correctIndex: 0,
      explanationAr: "إصبع واحد = 1.",
      hint1Ar: "انظر إلى إصبع واحد فقط.",
      hint2Ar: "الرمز هو 1.",
      difficulty: "basic",
      masteryWeight: 1,
      points: 5,
      skill: "العدّ",
    }),
  },
  objectivesLearnerAr: [
    "بنهاية الدرس أستطيع أن أعدّ حتى 3.",
    "أتعرّف الرموز 1 و2 و3.",
    "أربط كل عدد بمجموعة أشياء.",
    "أكتب 1 و2 و3 بخط واضح.",
  ],
  vocabulary: [
    { term: "عدد", definition: "رمز يخبرنا كم يوجد من الشيء.", example: "3 أقلام", nonExample: "لون القلم" },
    { term: "عدّ", definition: "قول الأعداد بالترتيب لمعرفة الكمية.", example: "واحد، اثنان، ثلاثة", nonExample: "قول أرقام عشوائية" },
    { term: "مجموعة", definition: "أشياء مجتمعة معاً لنعدّها.", example: "ثلاث كرات", nonExample: "كلمة بلا معنى كمية" },
  ],
  explanationSections: [
    {
      id: "exp-1",
      titleAr: "العدد 1",
      bodyAr: "عندما نرى شيئاً واحداً فقط نقول «واحد» ونكتب الرمز 1. لا نضيف شيئاً آخر.",
      visualAr: "★ = 1",
      workedExampleAr: "قلم واحد على الطاولة → نكتب 1.",
      altExplanationAr: "تخيّل درجة سلم واحدة فقط: هذه هي 1.",
      check: q({
        id: "exp-1-check",
        promptAr: "كم نجمة؟ ★",
        kind: "mcq",
        options: ["1", "2", "3"],
        correctIndex: 0,
        explanationAr: "نجمة واحدة = 1.",
        hint1Ar: "هل ترى أكثر من نجمة؟",
        hint2Ar: "الجواب هو الرمز الأول.",
        difficulty: "basic",
        masteryWeight: 1,
        points: 10,
        outcomeId: "o1",
        skill: "العدّ",
      }),
    },
    {
      id: "exp-2",
      titleAr: "العدد 2",
      bodyAr: "إذا أضفنا شيئاً ثانياً نقول «اثنان» ونكتب 2. الترتيب: بعد 1 يأتي 2.",
      visualAr: "★★ = 2",
      workedExampleAr: "تفاحتان → نعدّ: واحد، اثنان → نكتب 2.",
      altExplanationAr: "يدان مفتوحتان جزئياً بإصبعين = 2.",
      check: q({
        id: "exp-2-check",
        promptAr: "كم مربعاً؟ ■ ■",
        kind: "mcq",
        options: ["1", "2", "3"],
        correctIndex: 1,
        explanationAr: "مربعان = 2.",
        hint1Ar: "عدّ المربعات بإصبعك.",
        hint2Ar: "ليس واحداً وليس ثلاثة.",
        difficulty: "basic",
        masteryWeight: 1,
        points: 10,
        outcomeId: "o1",
        skill: "العدّ",
      }),
    },
    {
      id: "exp-3",
      titleAr: "العدد 3",
      bodyAr: "بعد 2 نضيف واحداً فنصل إلى 3. الرمز 3 يعني ثلاثة أشياء. لا نتخطّى 2 عند العدّ.",
      visualAr: "★★★ = 3",
      workedExampleAr: "ثلاث كرات: واحد، اثنان، ثلاثة → 3.",
      altExplanationAr: "درجات السلم: 1 ثم 2 ثم 3.",
      check: q({
        id: "exp-3-check",
        promptAr: "أي رمز يعني ثلاثة؟",
        kind: "mcq",
        options: ["1", "2", "3"],
        correctIndex: 2,
        explanationAr: "الرمز 3 يعني ثلاثة.",
        hint1Ar: "ابحث عن أكبر هذه الأعداد الصغيرة.",
        hint2Ar: "بعد 2 مباشرة.",
        difficulty: "basic",
        masteryWeight: 1,
        points: 10,
        outcomeId: "o1",
        skill: "العدّ",
      }),
    },
  ],
  guidedPractice: [
    q({
      id: "guided-1",
      promptAr: "اختر العدد الصحيح لمجموعة فيها شيئان: ● ●",
      kind: "mcq",
      options: ["1", "2", "3"],
      correctIndex: 1,
      explanationAr: "شيئان = 2.",
      hint1Ar: "عدّ النقطتين.",
      hint2Ar: "الجواب في الوسط.",
      difficulty: "basic",
      masteryWeight: 1,
      points: 10,
      outcomeId: "o2",
      skill: "المطابقة",
    }),
    q({
      id: "guided-2",
      promptAr: "ضع العدد الصحيح على خط الأعداد عند الموضع 3 (من 0 إلى 5).",
      kind: "number_line",
      numberLine: { min: 0, max: 5, target: 3, showJumps: true },
      correctAnswer: "3",
      acceptedAnswers: ["3", "٣"],
      explanationAr: "نبدأ من 0 ونقفز واحداً واحداً حتى 3.",
      hint1Ar: "اقفز ثلاث قفزات من الصفر.",
      hint2Ar: "الموضع بعد 2.",
      difficulty: "developing",
      masteryWeight: 1.2,
      points: 15,
      outcomeId: "o1",
      skill: "العدّ",
    }),
    q({
      id: "guided-3",
      promptAr: "طابق: مجموعة ★★★ مع العدد المناسب.",
      kind: "matching",
      pairs: [
        { left: "★", right: "1" },
        { left: "★★", right: "2" },
        { left: "★★★", right: "3" },
      ],
      explanationAr: "كل مجموعة تطابق عدد نجومها.",
      hint1Ar: "عدّ النجوم في كل صف.",
      hint2Ar: "★★★ = 3.",
      difficulty: "developing",
      masteryWeight: 1.2,
      points: 15,
      outcomeId: "o2",
      skill: "المطابقة",
    }),
  ],
  interactiveActivity: {
    titleAr: "أسقط العدد في الصندوق الصحيح",
    kind: "drag_drop",
    instructionsAr: "اسحب الأعداد 1 و2 و3 إلى المجموعات المناسبة.",
    questions: [
      q({
        id: "act-drag-1",
        promptAr: "أسقط كل عدد فوق مجموعته.",
        kind: "drag_drop",
        dragItems: ["1", "2", "3"],
        dropZones: [
          { id: "z1", labelAr: "🍎", accepts: ["1"] },
          { id: "z2", labelAr: "🍎🍎", accepts: ["2"] },
          { id: "z3", labelAr: "🍎🍎🍎", accepts: ["3"] },
        ],
        correctAnswer: "1→z1;2→z2;3→z3",
        explanationAr: "كل صندوق يأخذ عدد تفاحه.",
        hint1Ar: "ابدأ بالتفاحة الواحدة.",
        hint2Ar: "ثلاثة تفاح = 3.",
        difficulty: "proficient",
        masteryWeight: 1.5,
        points: 20,
        outcomeId: "o2",
        skill: "المطابقة",
      }),
    ],
  },
  realLife: {
    jordanContextAr: "في مقصف المدرسة: عدّ ثلاثة أكواب لبن أو ثلاث قطع خبز صغير.",
    homeAr: "عدّ ثلاثة وسائد أو ثلاثة كتب على الرف.",
    schoolAr: "عدّ ثلاثة أقلام في مقلمتك قبل الحصة.",
    communityAr: "عدّ ثلاثة أصدقاء يقفون في الطابور.",
  },
  collaboration: {
    boardType: "vocabulary_wall",
    promptAr: "اكتب أو ارسم مثالاً من بيتك للعدد 1 أو 2 أو 3 (كلمة قصيرة أو وصف).",
    anonymousAllowed: true,
    moderationRequired: true,
  },
  independentPractice: [
    q({
      id: "ind-basic",
      promptAr: "مجموعة فيها شيء واحد تُمثَّل بـ:",
      kind: "mcq",
      options: ["1", "2", "3"],
      correctIndex: 0,
      explanationAr: "شيء واحد = 1.",
      hint1Ar: "الأصغر.",
      hint2Ar: "رمز البداية.",
      difficulty: "basic",
      masteryWeight: 1,
      points: 10,
      outcomeId: "o2",
      skill: "المطابقة",
    }),
    q({
      id: "ind-dev",
      promptAr: "اكتب العدد الذي يأتي بعد 2.",
      kind: "fill_blank",
      correctAnswer: "3",
      acceptedAnswers: ["3", "٣", "ثلاثة"],
      explanationAr: "بعد 2 مباشرة يأتي 3.",
      hint1Ar: "واحد، اثنان، …؟",
      hint2Ar: "الرمز 3.",
      difficulty: "developing",
      masteryWeight: 1.2,
      points: 12,
      outcomeId: "o1",
      skill: "العدّ",
      commonErrorFeedbackAr: "إن كتبت 1 فقد عدت للخلف؛ إن كتبت 4 فقد تجاوزت 3.",
    }),
    q({
      id: "ind-prof",
      promptAr: "رتّب من الأصغر للأكبر: 3 ، 1 ، 2",
      kind: "ordering",
      orderItems: ["3", "1", "2"],
      correctOrder: ["1", "2", "3"],
      explanationAr: "الترتيب الصحيح 1 ثم 2 ثم 3.",
      hint1Ar: "ابدأ بأصغر عدد.",
      hint2Ar: "1 أصغر من الجميع.",
      difficulty: "proficient",
      masteryWeight: 1.5,
      points: 15,
      outcomeId: "o1",
      skill: "العدّ",
    }),
    q({
      id: "ind-challenge",
      promptAr: "أي مجموعة تختلف؟ (ليست 3)",
      kind: "mcq",
      options: ["★★★", "●●●", "■■"],
      correctIndex: 2,
      explanationAr: "■■ تمثل 2 وليست 3.",
      hint1Ar: "عدّ كل مجموعة.",
      hint2Ar: "ابحث عن التي فيها اثنان فقط.",
      difficulty: "challenge",
      masteryWeight: 2,
      points: 20,
      outcomeId: "o2",
      skill: "التمييز البصري",
    }),
  ],
  assessment: {
    titleAr: "تقييم قصير — الأعداد 1 و2 و3",
    passScorePercent: 70,
    questions: [
      q({
        id: "assess-1",
        promptAr: "ماذا يأتي بعد 1؟",
        kind: "mcq",
        options: ["3", "2", "0"],
        correctIndex: 1,
        explanationAr: "بعد 1 يأتي 2.",
        hint1Ar: "الترتيب التصاعدي.",
        hint2Ar: "ليس 3 مباشرة.",
        difficulty: "basic",
        masteryWeight: 1,
        points: 10,
        outcomeId: "o1",
        skill: "العدّ",
      }),
      q({
        id: "assess-2",
        promptAr: "كم نجمة؟ ★★★",
        kind: "mcq",
        options: ["2", "3", "1"],
        correctIndex: 1,
        explanationAr: "ثلاث نجوم = 3.",
        hint1Ar: "عدّ دون تكرار.",
        hint2Ar: "الجواب 3.",
        difficulty: "basic",
        masteryWeight: 1,
        points: 10,
        outcomeId: "o2",
        skill: "المطابقة",
      }),
      q({
        id: "assess-3",
        promptAr: "أي رمز يمثل اثنين؟",
        kind: "mcq",
        options: ["3", "1", "2"],
        correctIndex: 2,
        explanationAr: "2 يعني اثنين.",
        hint1Ar: "بين 1 و3.",
        hint2Ar: "الرمز 2.",
        difficulty: "developing",
        masteryWeight: 1,
        points: 10,
        outcomeId: "o1",
        skill: "الكتابة",
      }),
      q({
        id: "assess-4",
        promptAr: "صل المجموعة بعددها: ■ ■ ■",
        kind: "fill_blank",
        correctAnswer: "3",
        acceptedAnswers: ["3", "٣"],
        explanationAr: "ثلاثة مربعات = 3.",
        hint1Ar: "عدّ المربعات.",
        hint2Ar: "اكتب 3.",
        difficulty: "proficient",
        masteryWeight: 1.2,
        points: 15,
        outcomeId: "o2",
        skill: "المطابقة",
      }),
    ],
  },
  reflectionPromptsAr: [
    "ما الذي فهمته عن الأعداد 1 و2 و3؟",
    "ما الذي كان صعباً؟",
    "كم ثقتك الآن من 1 إلى 3؟",
    "أين تستخدم العدّ حتى 3 في بيتك أو مدرستك؟",
  ],
  nextStep: {
    nextLessonId: "u0-l2-numbers-45",
    nextLessonTitleAr: "العددان 4 ، 5",
    revisionGameEnabled: true,
    aiTutorEnabled: true,
  },
  reviewGameQuestionIds: ["assess-1", "assess-2", "assess-3", "ind-basic", "ind-dev", "guided-1"],
  aiTutorPolicy: {
    allowedTopics: ["الأعداد 1 و2 و3", "العدّ", "المطابقة", "خط الأعداد حتى 5"],
    forbidAnswerRevealBeforeAttempt: true,
    requireTeacherReviewOnLowConfidence: true,
    noUncontrolledInternet: true,
  },
};
