import type { InventoryItem } from "@/src/lib/jordan-books/schema/types";

/**
 * Grade 1 Semester 1 inventory — subject list from jordan-curriculum.js
 * (subject-list-verified). Book-type rows follow NCCD catalogue pattern.
 * Exact PDF edition years: NEEDS VERIFICATION on live NCCD page.
 */
export const G1_SEM1_INVENTORY: InventoryItem[] = [
  {
    id: "jo-g1-s1-math-student",
    grade: "1",
    gradeAr: "الصف الأول",
    semester: "1",
    subjectAr: "الرياضيات",
    bookType: "student",
    officialTitleAr: "الرياضيات — كتاب الطالب — الفصل الدراسي الأول",
    officialSourceUrl: "https://www.nccd.gov.jo/ar/pages/TextBooksGrade/68",
    rightsStatus: "official_link_only",
    availabilityStatus: "official_catalog_listed",
    verificationDate: "2026-07-28",
    notes: "Interactive SOS book is original aligned content; official PDF linked only.",
  },
  {
    id: "jo-g1-s1-math-exercises",
    grade: "1",
    gradeAr: "الصف الأول",
    semester: "1",
    subjectAr: "الرياضيات",
    bookType: "activity",
    officialTitleAr: "الرياضيات — كتاب التمارين — الفصل الدراسي الأول",
    officialSourceUrl: "https://www.nccd.gov.jo/ar/pages/TextBooksGrade/68",
    rightsStatus: "official_link_only",
    availabilityStatus: "official_catalog_listed",
    verificationDate: "2026-07-28",
  },
  {
    id: "jo-g1-s1-math-teacher",
    grade: "1",
    gradeAr: "الصف الأول",
    semester: "1",
    subjectAr: "الرياضيات",
    bookType: "teacher_guide",
    officialTitleAr: "الرياضيات — دليل المعلم — الفصل الدراسي الأول",
    officialSourceUrl: "https://www.nccd.gov.jo/ar/pages/TextBooksGrade/68",
    rightsStatus: "official_link_only",
    availabilityStatus: "official_catalog_listed",
    verificationDate: "2026-07-28",
  },
  {
    id: "jo-g1-s1-arabic-student",
    grade: "1",
    gradeAr: "الصف الأول",
    semester: "1",
    subjectAr: "اللغة العربية",
    bookType: "student",
    officialTitleAr: "اللغة العربية — كتاب الطالب — الفصل الدراسي الأول",
    officialSourceUrl: "https://www.nccd.gov.jo/ar/pages/TextBooksGrade/68",
    rightsStatus: "rights_review_required",
    availabilityStatus: "needs_verification",
    verificationDate: "2026-07-28",
    notes: "NEEDS VERIFICATION: confirm exact edition title on NCCD page before structuring.",
  },
  {
    id: "jo-g1-s1-english-student",
    grade: "1",
    gradeAr: "الصف الأول",
    semester: "1",
    subjectAr: "اللغة الإنجليزية",
    bookType: "student",
    officialTitleAr: "English — Student Book — Semester 1",
    officialSourceUrl: "https://www.nccd.gov.jo/ar/pages/TextBooksGrade/68",
    rightsStatus: "rights_review_required",
    availabilityStatus: "needs_verification",
    verificationDate: "2026-07-28",
  },
  {
    id: "jo-g1-s1-science-student",
    grade: "1",
    gradeAr: "الصف الأول",
    semester: "1",
    subjectAr: "العلوم",
    bookType: "student",
    officialTitleAr: "العلوم — كتاب الطالب — الفصل الدراسي الأول",
    officialSourceUrl: "https://www.nccd.gov.jo/ar/pages/TextBooksGrade/68",
    rightsStatus: "rights_review_required",
    availabilityStatus: "needs_verification",
    verificationDate: "2026-07-28",
  },
  {
    id: "jo-g1-s1-islamic-student",
    grade: "1",
    gradeAr: "الصف الأول",
    semester: "1",
    subjectAr: "التربية الإسلامية",
    bookType: "student",
    officialTitleAr: "التربية الإسلامية — كتاب الطالب — الفصل الدراسي الأول",
    officialSourceUrl: "https://www.nccd.gov.jo/ar/pages/TextBooksGrade/68",
    rightsStatus: "rights_review_required",
    availabilityStatus: "needs_verification",
    verificationDate: "2026-07-28",
  },
  {
    id: "jo-g1-s1-social-student",
    grade: "1",
    gradeAr: "الصف الأول",
    semester: "1",
    subjectAr: "الدراسات الاجتماعية",
    bookType: "student",
    officialTitleAr: "الدراسات الاجتماعية — كتاب الطالب — الفصل الدراسي الأول",
    officialSourceUrl: "https://www.nccd.gov.jo/ar/pages/TextBooksGrade/68",
    rightsStatus: "rights_review_required",
    availabilityStatus: "needs_verification",
    verificationDate: "2026-07-28",
  },
  {
    id: "jo-g1-s1-digital-skills",
    grade: "1",
    gradeAr: "الصف الأول",
    semester: "1",
    subjectAr: "المهارات الرقمية",
    bookType: "student",
    officialTitleAr: "المهارات الرقمية — مواد الفصل الدراسي الأول",
    officialSourceUrl: "https://www.nccd.gov.jo/ar/pages/TextBooksGrade/68",
    rightsStatus: "needs_verification",
    availabilityStatus: "needs_verification",
    verificationDate: "2026-07-28",
  },
  {
    id: "jo-g1-s1-pe",
    grade: "1",
    gradeAr: "الصف الأول",
    semester: "1",
    subjectAr: "التربية الرياضية",
    bookType: "support",
    officialTitleAr: "التربية الرياضية — مواد الفصل الدراسي الأول",
    officialSourceUrl: "https://www.nccd.gov.jo/ar/pages/TextBooksGrade/68",
    rightsStatus: "needs_verification",
    availabilityStatus: "needs_verification",
    verificationDate: "2026-07-28",
  },
  {
    id: "jo-g1-s1-arts",
    grade: "1",
    gradeAr: "الصف الأول",
    semester: "1",
    subjectAr: "التربية الفنية والموسيقية والمسرحية",
    bookType: "support",
    officialTitleAr: "التربية الفنية والموسيقية والمسرحية — مواد الفصل الدراسي الأول",
    officialSourceUrl: "https://www.nccd.gov.jo/ar/pages/TextBooksGrade/68",
    rightsStatus: "needs_verification",
    availabilityStatus: "needs_verification",
    verificationDate: "2026-07-28",
  },
];

export const OFFICIAL_SOURCES = [
  {
    name: "NCCD textbook catalogue",
    url: "https://nccd.gov.jo/Ar/Pages/textbooks",
    authorityType: "official-authority",
  },
  {
    name: "NCCD Grade 1 textbooks",
    url: "https://www.nccd.gov.jo/ar/pages/TextBooksGrade/68",
    authorityType: "official-authority",
  },
  {
    name: "Jordan Ministry of Education — curricula administration",
    url: "https://moe.gov.jo/ar/%D8%A5%D8%AF%D8%A7%D8%B1%D8%A9-%D8%A7%D9%84%D9%85%D9%86%D8%A7%D9%87%D8%AC-%D9%88%D8%A7%D9%84%D9%83%D8%AA%D8%A8-%D8%A7%D9%84%D9%85%D8%AF%D8%B1%D8%B3%D9%8A%D8%A9",
    authorityType: "ministry",
  },
];
