'use client';
import {useMemo,useState} from 'react';
import {InnerNav} from '../components';
const exams=[
{family:'SAT',date:'22 أغسطس 2026',deadline:'7 أغسطس 2026',scope:'عالمي',title:'SAT August',url:'https://satsuite.collegeboard.org/dates/august-22-2026-sat-test-date'},
{family:'ACT',date:'19 سبتمبر 2026',deadline:'14 أغسطس 2026',scope:'الولايات المتحدة ومناطقها',title:'ACT September',url:'https://www.act.org/content/act/en/products-and-services/the-act/registration/test-dates.html'},
{family:'ACT',date:'17 أكتوبر 2026',deadline:'11 سبتمبر 2026',scope:'الولايات المتحدة ومناطقها',title:'ACT October',url:'https://www.act.org/content/act/en/products-and-services/the-act/registration/test-dates.html'},
{family:'ACT',date:'12 ديسمبر 2026',deadline:'6 نوفمبر 2026',scope:'الولايات المتحدة ومناطقها',title:'ACT December',url:'https://www.act.org/content/act/en/products-and-services/the-act/registration/test-dates.html'},
{family:'Cambridge',date:'نوفمبر 2026',deadline:'حسب المنطقة والمركز',scope:'مناطق Cambridge الإدارية',title:'IGCSE / O Level / AS & A Level',url:'https://www.cambridgeinternational.org/exam-administration/cambridge-exams-officers-guide/phase-1-preparation/timetabling-exams/exam-timetables'},
{family:'Pearson',date:'28 أكتوبر–19 نوفمبر 2026',deadline:'حسب المركز',scope:'International GCSE',title:'Pearson Edexcel November',url:'https://qualifications.pearson.com/en/support/support-topics/exams/exam-timetables.html'},
{family:'IB',date:'نوفمبر 2026',deadline:'حسب مدرسة IB',scope:'DP / CP',title:'IB November examination session',url:'https://ibo.org/programmes/diploma-programme/assessment-and-exams/exam-schedule/'},
{family:'IELTS',date:'مواعيد شهرية حسب البلد',deadline:'حسب المركز',scope:'عالمي',title:'IELTS Academic / General',url:'https://ielts.org/test-centres'},
{family:'TOEFL',date:'مواعيد حسب البلد والمركز',deadline:'يفضل قبل القبول بـ2–3 أشهر',scope:'عالمي',title:'TOEFL iBT',url:'https://www.ets.org/toefl/test-takers/ibt/schedule.html'}];
export default function ExamCalendar(){const [family,setFamily]=useState('الكل'),[saved,setSaved]=useState([]);const rows=useMemo(()=>exams.filter(x=>family==='الكل'||x.family===family),[family]);return <div className="os-page phase11-legacy-page"><InnerNav active="calendar"/><main className="os-page-content calendar-page"><header className="calendar-hero"><div><span>GLOBAL EXAM CALENDAR</span><h1>رزنامة الاختبارات العالمية</h1><p>المواعيد الرسمية، التسجيل، والتنبيه المبكر ضمن صفحة الطالب. قد تختلف المراكز المتاحة حسب الدولة.</p></div><div><b>{saved.length}</b><small>تنبيهات محفوظة</small></div></header><section className="calendar-toolbar"><label>الاختبار<select value={family} onChange={e=>setFamily(e.target.value)}>{['الكل',...new Set(exams.map(x=>x.family))].map(x=><option key={x}>{x}</option>)}</select></label><a href="/notifications">فتح تنبيهات الطالب</a></section><section className="calendar-list">{rows.map((x,i)=><article key={`${x.title}-${x.date}`}><div className="calendar-date"><b>{x.date}</b><small>{x.scope}</small></div><div><small>{x.family}</small><h2>{x.title}</h2><p>آخر موعد مسجل: {x.deadline}</p></div><div className="calendar-actions"><button onClick={()=>setSaved(s=>s.includes(i)?s.filter(n=>n!==i):[...s,i])}>{saved.includes(i)?'✓ تم حفظ التنبيه':'🔔 نبهني'}</button><a href={x.url} target="_blank" rel="noreferrer">المصدر الرسمي ↗</a></div></article>)}</section><div className="calendar-warning">تتحقق المنصة من المواعيد دوريًا، لكن يجب تأكيد الموعد والمنطقة والمركز قبل الدفع أو السفر.</div></main></div>}
