import { InnerNav } from '../components';

const stages=[['🧸','الطفولة المبكرة','اكتشاف الفضول واللغة والقدرات الأساسية'],['🎒','المدرسة','منهاج شخصي ودروس ومعلمون واختبارات'],['🎓','الجامعة','اختيار التخصص والقبول والبحث والشهادات'],['💼','المهنة','ربط المهارات بالوظائف والفجوات والتطور'],['🚀','ريادة الأعمال','تعلم عملي ومشاريع وإرشاد ونمو الأعمال'],['∞','التعلم مدى الحياة','هوية تعليمية تتطور مع الإنسان دائمًا']];
const agents=[['✦','AI Teacher','ينشئ ويقدم دروسًا وشرحًا متكيفًا مع المستوى والمنهاج واللغة.'],['◈','AI Tutor','يرشد أثناء الحل ويكشف الخطأ في الفهم بدون كشف الجواب فورًا.'],['◎','AI Mentor','يتابع الأهداف والعادات والدافعية والتقدم طويل المدى.'],['↗','AI Career Advisor','يربط المهارات بالوظائف والمسارات والشهادات المطلوبة.'],['⌂','AI Parent Assistant','يعطي ولي الأمر رؤية مناسبة للعمر مع احترام خصوصية الطالب.'],['🎓','AI Admissions Advisor','يقارن البرامج والمتطلبات ويجهز الطالب للتقديم.'],['✈','AI Visa Advisor','معلومات وقوائم وثائق من مصادر رسمية بدون ضمان القرار.'],['⌕','AI Research Assistant','يساعد في البحث والمصادر والتوثيق والنزاهة العلمية.']];
const experiences=[['▶','دروس مسجلة تفاعلية'],['◉','دروس مولدة بالذكاء'],['♙','تدريس خاص وجماعي'],['⌂','مراكز تعلم فعلية'],['⚗','مختبرات افتراضية'],['◇','مشاريع وملفات إنجاز'],['✓','اختبارات وإتقان'],['▣','شهادات موثقة'],['✎','مساحة كتابة وحل'],['◌','AR / VR مستقبلًا'],['☷','حصص مباشرة مسجلة'],['🌐','لغات وإتاحة عالمية']];
export default function EcosystemPage(){return <div className="os-page"><InnerNav active="ecosystem"/><main className="os-page-content"><section className="eco-hero"><span>THE COMPLETE SUCCESS OS VISION</span><h1>نظام تعليم واحد يرافق الإنسان طوال حياته</h1><p>SUCCESS OS ليس LMS ولا موقع دورات. هو بنية تعليمية تربط التعلم والمهارات والمعلمين والمؤسسات والفرص حول هوية تعليمية واحدة يمتلكها المتعلم.</p><div className="eco-pill-row"><b>الطالب في المركز</b><b>القرار النهائي للإنسان</b><b>ذكاء قابل للتفسير</b><b>خصوصية وأمان</b><b>عربي وإنجليزي ثم العالم</b></div></section><Section tag="رحلة الإنسان" title="من الطفولة إلى التعلم مدى الحياة" text="كل مرحلة تبني على ما قبلها، والجواز التعليمي يحفظ التقدم والأدلة بدل أن تبدأ حياة المتعلم من الصفر كل مرة."><div className="life-stages">{stages.map(([icon,title,text],i)=><article className="os-card life-card" key={title}><span>{icon}</span><i>0{i+1}</i><h3>{title}</h3><p>{text}</p></article>)}</div></Section><Section tag="منظومة الذكاء" title="ثمانية وكلاء متخصصين. عقل منسق واحد." text="الموجه المركزي يرسل كل سؤال للوكيل المناسب، ويشارك فقط المعلومات المسموح بها من الجواز التعليمي."><div className="agent-grid">{agents.map(([icon,title,text])=><article className="os-card agent-card" key={title}><span>{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></Section><Section tag="الشبكة العالمية" title="كل أطراف التعليم في منظومة واحدة" text="لا يستبدل SUCCESS OS المدارس والجامعات والمعلمين، بل يربطهم حول رحلة المتعلم."><div className="network-map"><div className="network-column">{['الطلاب وأولياء الأمور','المعلمون والمدربون','المدارس ومراكز التعلم','الجامعات والكليات'].map(x=><div className="network-node" key={x}>{x}</div>)}</div><div className="network-core"><div><strong>SUCCESS OS</strong><small>Education Passport + AI</small></div></div><div className="network-column">{['جهات المنح والجمعيات','أصحاب العمل','الباحثون والمنظمات','الحكومات والاعتماد'].map(x=><div className="network-node" key={x}>{x}</div>)}</div></div></Section><Section tag="تجربة التعلم" title="التعلم ليس فيديو واختبارًا فقط" text="المنصة تجمع التعلم الرقمي والإنساني والفعلي، وتقيس الفهم من خلال أدلة متعددة."><div className="experience-grid">{experiences.map(([icon,text])=><div className="os-card experience-item" key={text}><span>{icon}</span><b>{text}</b></div>)}</div></Section><Section tag="التنفيذ المرحلي" title="رؤية عالمية، وبداية مركزة وقابلة للقياس" text="نبني قيمة كاملة في كل مرحلة بدل فتح عشرات الوحدات بدون رحلة طالب ناجحة."><div className="roadmap"><Road phase="المرحلة 0" title="الأساس" text="الدستور والحوكمة والمحتوى والبيانات والجودة."/><Road phase="المرحلة 1" title="MVP التعلم المتصل" text="الجواز والتشخيص والخطة والدروس والذكاء والمعلم."/><Road phase="المرحلة 2" title="شبكة المؤسسات" text="بوابات المدارس والمراكز والجامعات والتحقق."/><Road phase="المرحلة 3+" title="الفرص العالمية" text="منح وقبول ومهن وبحث وريادة أعمال وتكامل دولي."/></div></Section></main></div>}
function Section({tag,title,text,children}){return <section className="eco-section"><header className="eco-section-head"><small>{tag}</small><h2>{title}</h2><p>{text}</p></header>{children}</section>}
function Road({phase,title,text}){return <article className="os-card roadmap-card"><small>{phase}</small><h3>{title}</h3><p>{text}</p></article>}

