import type { AdmissionProfileInput, ApplicationPersonal, Institution } from "@/src/types/admission";

export function buildApplicationEmailHtml(input: {
  institution: Institution;
  personal: ApplicationPersonal;
  profile: AdmissionProfileInput;
  message?: string;
  applicationId: string;
}) {
  const { institution, personal, profile, message, applicationId } = input;
  const rows = [
    ["Applicant", personal.fullName],
    ["Email", personal.email],
    ["Phone", personal.phone],
    ["Date of birth", personal.dateOfBirth],
    ["Address", personal.address || "—"],
    ["Nationality", profile.nationality],
    ["GPA", String(profile.gpa)],
    ["Target degree", profile.targetDegree],
    ["Major", profile.major],
    ["Preferred study country", profile.preferredStudyCountry || "—"],
  ];

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Admission application — ${escapeHtml(institution.name)}</title>
</head>
<body style="margin:0;padding:0;background:#f7f2f3;font-family:Georgia,'Times New Roman',serif;color:#2a1216;">
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f7f2f3;padding:28px 12px;">
    <tr>
      <td align="center">
        <table role="presentation" width="640" cellpadding="0" cellspacing="0" style="background:#ffffff;border:1px solid #ead9db;border-radius:16px;overflow:hidden;">
          <tr>
            <td style="background:linear-gradient(135deg,#4b0a11,#9e1722);color:#fff;padding:28px 32px;">
              <div style="font:700 11px Arial,sans-serif;letter-spacing:.16em;text-transform:uppercase;opacity:.85;">SUCCESS OS</div>
              <h1 style="margin:10px 0 6px;font-size:26px;line-height:1.25;">Official admission application</h1>
              <p style="margin:0;font:400 14px Arial,sans-serif;color:#f2dadd;">
                Submitted via SUCCESS OS dual-route admissions · Reference ${escapeHtml(applicationId)}
              </p>
            </td>
          </tr>
          <tr>
            <td style="padding:28px 32px;">
              <p style="margin:0 0 18px;font:400 15px Arial,sans-serif;line-height:1.7;color:#4d3439;">
                Dear Admissions Office at <strong>${escapeHtml(institution.name)}</strong>,
                please find below a complete application package for the applicant named herein.
                Academic transcript and passport PDFs are attached.
              </p>
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;font:400 14px Arial,sans-serif;">
                ${rows
                  .map(
                    ([k, v]) => `
                  <tr>
                    <td style="padding:10px 0;border-bottom:1px solid #f0e6e7;width:38%;color:#7a6368;font-weight:700;">${escapeHtml(k || "")}</td>
                    <td style="padding:10px 0;border-bottom:1px solid #f0e6e7;color:#2a1216;">${escapeHtml(v || "—")}</td>
                  </tr>`,
                  )
                  .join("")}
              </table>
              ${
                message
                  ? `<div style="margin-top:22px;padding:16px;border-radius:12px;background:#fff8f8;border:1px solid #f0e0e2;">
                      <div style="font:700 12px Arial,sans-serif;color:#9e1722;margin-bottom:8px;">Applicant message</div>
                      <p style="margin:0;font:400 14px Arial,sans-serif;line-height:1.7;white-space:pre-wrap;">${escapeHtml(message)}</p>
                    </div>`
                  : ""
              }
              <p style="margin:24px 0 0;font:400 12px Arial,sans-serif;color:#8a7477;line-height:1.6;">
                This message was generated by SUCCESS OS on behalf of the student.
                Please reply directly to the applicant email above.
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
