'use client';
import { useState } from 'react';
import { InnerNav } from '../components';

export default function TutorPage(){
  const [text,setText]=useState(''); const [messages,setMessages]=useState([]);
  function ask(e){e.preventDefault();if(!text.trim())return;setMessages(m=>[...m,{user:text,ai:'ممتاز. قبل ما نعوض بالأرقام، شو القانون الذي يربط فرق الجهد والتيار والمقاومة؟ اكتب القانون بطريقتك وأنا أكمل معك خطوة بخطوة.'}]);setText('')}
  return <div className="os-page phase11-legacy-page"><InnerNav active="tutor"/><main className="os-page-content"><header className="os-page-head"><span className="tag">SUCCESS AI TUTOR</span><h1>اسأل. فكّر. افهم.</h1><p>معلم ذكي يساعدك حسب منهاجك ومستواك، يعطيك تلميحات ويكتشف الخطأ في فهمك بدون ما يرمي الحل مباشرة.</p></header><div className="tutor-layout"><section className="os-card tutor-main"><div className="tutor-head"><span className="tutor-ai">✦</span><div><strong>المعلم الذكي للفيزياء</strong><small>مرتبط بخطتك ودرس الدوائر الكهربائية</small></div><span className="tutor-mode">● وضع التعلم الموثق</span></div><div className="tutor-messages"><div className="tutor-bubble user">بطارية 12 V موصولة بمقاومة 4 Ω. من وين أبدأ؟</div><div className="tutor-bubble ai">ابدأ بتحديد المعطيات: فرق الجهد V = 12 V والمقاومة R = 4 Ω. الآن ما هي الكمية المطلوبة؟ وهل تتذكر قانون أوم؟<small>المصدر: الدوائر الكهربائية • قانون أوم • Edexcel AS Physics</small></div>{messages.map((m,i)=><span key={i} style={{display:'contents'}}><div className="tutor-bubble user">{m.user}</div><div className="tutor-bubble ai">{m.ai}<small>إرشاد تعليمي مبني على سياق الدرس</small></div></span>)}</div><form className="tutor-input" onSubmit={ask}><input value={text} onChange={e=>setText(e.target.value)} placeholder="اكتب سؤالك في الفيزياء أو الكيمياء..."/><button>↑</button></form></section><aside className="os-card tutor-context"><h3>سياق تعلمك الحالي</h3><Context icon="⚡" title="الدرس" text="الشحنة والتيار"/><Context icon="◎" title="الهدف" text="إتقان الدوائر قبل 20 يوليو"/><Context icon="◈" title="مستوى الإتقان" text="61% • يحتاج تدريب"/><div className="tutor-actions"><button>اشرحها بطريقة ثانية</button><button>أعطني سؤالًا مشابهًا</button><button>أحتاج تلميحًا فقط</button><button>حوّلني لمعلم حقيقي</button></div></aside></div></main></div>
}
function Context({icon,title,text}){return <div className="context-item"><span>{icon}</span><div><strong>{title}</strong><small>{text}</small></div></div>}

