import type { InteractiveLessonDefinition } from "@/src/lib/interactive-lesson/types";

/** Original Success OS G1 number-line addition — interactive prototype. */
export const JORDAN_G1_MATH_INTERACTIVE: InteractiveLessonDefinition = {
  schema: "success-os.interactive-lesson.v1",
  lessonId: "jordan-g1-math-number-line-addition",
  country: "Jordan",
  curriculum: "national",
  grade: "1",
  subject: "Mathematics",
  unit: "Addition",
  title: {
    ar: "الجمع بخط الأعداد",
    en: "Addition on the Number Line",
  },
  preparedBy: "Prepared by Mr Waseem Allabadi",
  teacherName: { ar: "أ. لاما النوري", en: "Ms. Lama Al-Nouri" },
  teacherTitle: { ar: "معلّمة مساعدة", en: "AI Assistant Teacher" },
  objectives: [
    {
      ar: "أشرح معنى خط الأعداد.",
      en: "I can explain what a number line is.",
    },
    {
      ar: "أحل مسائل جمع بسيطة بالقفز لليمين.",
      en: "I can solve simple addition by jumping right.",
    },
    {
      ar: "أتحقق من إجابتي بثقة.",
      en: "I can check my answer with confidence.",
    },
  ],
  estimatedMinutes: 12,
  nextLessonHint: {
    ar: "الدرس التالي المقترح: الطرح بخط الأعداد",
    en: "Suggested next: Subtraction on the number line",
  },
  scenes: [
    {
      sceneId: "hook",
      sceneType: "hook",
      durationMs: 12000,
      learningGoal: { ar: "ترحيب وتشويق", en: "Warm welcome" },
      narration: {
        ar: "مرحبا يا بطل الصف الأول! أنا المعلمة المساعدة لاما. اليوم نلعب لعبة القفز على خط الأعداد لنتعلم الجمع.",
        en: "Hello Grade 1 hero! I am assistant teacher Lama. Today we jump on the number line to learn addition.",
      },
      captions: {
        ar: "اليوم نتعلم الجمع بالقفز على خط الأعداد",
        en: "Today we learn addition by jumping on the number line",
      },
      board: "title",
      visualTimeline: [{ atMs: 400, action: "show_equation", value: "3 + 2 = ?" }],
      interactionType: "none",
      correctAnswer: 0,
      accessibilityText: {
        ar: "مقدمة الدرس مع معادلة 3 زائد 2",
        en: "Lesson intro showing 3 plus 2",
      },
      completionRule: "auto",
      audio: {
        ar: "/interactive-lessons/g1-math/audio/ar/hook.mp3",
        en: "/interactive-lessons/g1-math/audio/en/hook.mp3",
      },
    },
    {
      sceneId: "objective",
      sceneType: "objective",
      durationMs: 10000,
      learningGoal: { ar: "هدف الدرس", en: "Lesson goal" },
      narration: {
        ar: "هدفنا اليوم: نبدأ من عدد، ثم نقفز لليمين بعدد الجمع، ونجد الناتج بثقة.",
        en: "Our goal: start at a number, jump right by the addend, and find the sum confidently.",
      },
      captions: {
        ar: "ابدأ → اقفز لليمين → الناتج",
        en: "Start → jump right → sum",
      },
      board: "equation",
      visualTimeline: [{ atMs: 300, action: "show_equation", value: "ابدأ → قفز → ناتج" }],
      interactionType: "none",
      correctAnswer: 0,
      accessibilityText: { ar: "عرض هدف الدرس", en: "Show lesson objective" },
      completionRule: "auto",
      audio: {
        ar: "/interactive-lessons/g1-math/audio/ar/objective.mp3",
        en: "/interactive-lessons/g1-math/audio/en/objective.mp3",
      },
    },
    {
      sceneId: "prereq",
      sceneType: "prerequisite",
      durationMs: 8000,
      learningGoal: { ar: "تحقق سريع", en: "Quick check" },
      narration: {
        ar: "قبل ما نبدأ: أي رقم أكبر؟ اضغط على الرقم الأكبر.",
        en: "Before we start: which number is bigger? Tap the bigger number.",
      },
      captions: { ar: "أي رقم أكبر؟", en: "Which number is bigger?" },
      board: "objects",
      visualTimeline: [{ atMs: 200, action: "show_objects", count: 2 }],
      interactionType: "mcq",
      question: { ar: "أي رقم أكبر؟", en: "Which number is bigger?" },
      answerOptions: [
        { ar: "2", en: "2" },
        { ar: "5", en: "5" },
        { ar: "3", en: "3" },
      ],
      correctAnswer: 1,
      firstHint: { ar: "فكّر: أين نذهب على الخط ليصير الرقم أكبر؟", en: "Think: which way makes numbers bigger?" },
      secondExplanation: {
        ar: "على خط الأعداد، الأرقام تكبر لليمين. إذن 5 أكبر من 2 و3.",
        en: "On a number line, numbers get bigger to the right. So 5 is bigger.",
      },
      correctFeedback: { ar: "برافو! 5 أكبر.", en: "Great! 5 is bigger." },
      incorrectFeedback: { ar: "حاول مرة ثانية بهدوء.", en: "Try again calmly." },
      accessibilityText: { ar: "سؤال: أي رقم أكبر بين 2 و5 و3", en: "Question: bigger of 2, 5, 3" },
      completionRule: "interaction",
      audio: {
        ar: "/interactive-lessons/g1-math/audio/ar/prereq.mp3",
        en: "/interactive-lessons/g1-math/audio/en/prereq.mp3",
      },
    },
    {
      sceneId: "explain-line",
      sceneType: "explain",
      durationMs: 14000,
      learningGoal: { ar: "ما هو خط الأعداد؟", en: "What is a number line?" },
      narration: {
        ar: "خط الأعداد خط مستقيم. الأرقام مرتبة من اليسار إلى اليمين. كل قفزة لليمين تضيف واحداً.",
        en: "A number line is a straight line. Numbers go left to right. Each jump right adds one.",
      },
      captions: { ar: "اليسار أصغر · اليمين أكبر", en: "Left smaller · right bigger" },
      board: "numberline",
      visualTimeline: [
        { atMs: 300, action: "show_line" },
        { atMs: 1800, action: "highlight", value: 0 },
        { atMs: 3200, action: "highlight", value: 5 },
        { atMs: 5000, action: "highlight", value: 10 },
      ],
      interactionType: "none",
      correctAnswer: 0,
      accessibilityText: { ar: "شرح خط الأعداد", en: "Explain number line" },
      completionRule: "auto",
      audio: {
        ar: "/interactive-lessons/g1-math/audio/ar/explain-line.mp3",
        en: "/interactive-lessons/g1-math/audio/en/explain-line.mp3",
      },
    },
    {
      sceneId: "demo-3-plus-2",
      sceneType: "demo",
      durationMs: 16000,
      learningGoal: { ar: "عرض 3+2", en: "Demo 3+2" },
      narration: {
        ar: "شاهدوا: ثلاثة زائد اثنين. نقف عند 3، ثم قفزة إلى 4، ثم قفزة إلى 5. الناتج خمسة.",
        en: "Watch: three plus two. Stand on 3, jump to 4, then to 5. The sum is five.",
      },
      captions: { ar: "3 → 4 → 5", en: "3 → 4 → 5" },
      board: "jumps",
      visualTimeline: [
        { atMs: 400, action: "show_line" },
        { atMs: 1200, action: "show_equation", value: "3 + 2 = ?" },
        { atMs: 2800, action: "place_start", value: 3 },
        { atMs: 5200, action: "jump", from: 3, to: 4 },
        { atMs: 7800, action: "jump", from: 4, to: 5 },
        { atMs: 11000, action: "show_equation", value: "3 + 2 = 5" },
        { atMs: 12500, action: "celebrate" },
      ],
      interactionType: "none",
      correctAnswer: 0,
      accessibilityText: { ar: "عرض متحرك لثلاثة زائد اثنين", en: "Animated demo of 3+2" },
      completionRule: "auto",
      audio: {
        ar: "/interactive-lessons/g1-math/audio/ar/demo-3-plus-2.mp3",
        en: "/interactive-lessons/g1-math/audio/en/demo-3-plus-2.mp3",
      },
    },
    {
      sceneId: "guided-1",
      sceneType: "your_turn",
      durationMs: 8000,
      learningGoal: { ar: "دورك: 3+2", en: "Your turn: 3+2" },
      narration: {
        ar: "دورك الآن. ثلاثة زائد اثنين يساوي كام؟ اختر الإجابة.",
        en: "Your turn. What is three plus two? Choose the answer.",
      },
      captions: { ar: "3 + 2 = ؟", en: "3 + 2 = ?" },
      board: "jumps",
      visualTimeline: [
        { atMs: 200, action: "show_line" },
        { atMs: 400, action: "place_start", value: 3 },
        { atMs: 800, action: "show_equation", value: "3 + 2 = ?" },
      ],
      interactionType: "mcq",
      question: { ar: "٣ + ٢ = ؟", en: "3 + 2 = ?" },
      answerOptions: [
        { ar: "4", en: "4" },
        { ar: "5", en: "5" },
        { ar: "6", en: "6" },
      ],
      correctAnswer: 1,
      firstHint: {
        ar: "ابدأ من 3، ثم اقفز قفزتين لليمين.",
        en: "Start at 3, then make two jumps right.",
      },
      secondExplanation: {
        ar: "من 3 إلى 4 قفزة، ومن 4 إلى 5 قفزة. إذن الناتج 5.",
        en: "From 3 to 4, then 4 to 5. So the answer is 5.",
      },
      correctFeedback: { ar: "أحسنت! الناتج 5.", en: "Well done! The sum is 5." },
      incorrectFeedback: { ar: "ليس بعد. فكّر بالقفزات.", en: "Not yet. Think about the jumps." },
      accessibilityText: { ar: "سؤال تفاعلي ثلاثة زائد اثنين", en: "Interactive 3+2" },
      completionRule: "interaction",
      easierBoard: "jumps",
      easierVisualTimeline: [
        { atMs: 200, action: "show_line" },
        { atMs: 500, action: "place_start", value: 3 },
        { atMs: 1500, action: "jump", from: 3, to: 4 },
        { atMs: 3000, action: "jump", from: 4, to: 5 },
        { atMs: 4500, action: "show_equation", value: "3 + 2 = 5" },
      ],
      audio: {
        ar: "/interactive-lessons/g1-math/audio/ar/guided-1.mp3",
        en: "/interactive-lessons/g1-math/audio/en/guided-1.mp3",
      },
    },
    {
      sceneId: "guided-2-demo",
      sceneType: "guided",
      durationMs: 14000,
      learningGoal: { ar: "مثال ثانٍ 2+3", en: "Second example 2+3" },
      narration: {
        ar: "مثال آخر: اثنان زائد ثلاثة. نبدأ من 2، ثم ثلاث قفزات: 3، 4، 5. الناتج أيضاً خمسة.",
        en: "Another example: two plus three. Start at 2, then three jumps: 3, 4, 5. Also five.",
      },
      captions: { ar: "2 → 3 → 4 → 5", en: "2 → 3 → 4 → 5" },
      board: "jumps",
      visualTimeline: [
        { atMs: 300, action: "show_line" },
        { atMs: 1000, action: "show_equation", value: "2 + 3 = ?" },
        { atMs: 2200, action: "place_start", value: 2 },
        { atMs: 4200, action: "jump", from: 2, to: 3 },
        { atMs: 6200, action: "jump", from: 3, to: 4 },
        { atMs: 8200, action: "jump", from: 4, to: 5 },
        { atMs: 10500, action: "show_equation", value: "2 + 3 = 5" },
      ],
      interactionType: "none",
      correctAnswer: 0,
      accessibilityText: { ar: "عرض اثنين زائد ثلاثة", en: "Demo 2+3" },
      completionRule: "auto",
      audio: {
        ar: "/interactive-lessons/g1-math/audio/ar/guided-2-demo.mp3",
        en: "/interactive-lessons/g1-math/audio/en/guided-2-demo.mp3",
      },
    },
    {
      sceneId: "practice-2-plus-3",
      sceneType: "practice",
      durationMs: 8000,
      learningGoal: { ar: "تمرين 2+3", en: "Practice 2+3" },
      narration: {
        ar: "جرّب أنت: اثنان زائد ثلاثة. اضغط الرقم الصحيح.",
        en: "Try it: two plus three. Tap the correct number.",
      },
      captions: { ar: "2 + 3 = ؟", en: "2 + 3 = ?" },
      board: "jumps",
      visualTimeline: [
        { atMs: 200, action: "show_line" },
        { atMs: 400, action: "place_start", value: 2 },
        { atMs: 700, action: "show_equation", value: "2 + 3 = ?" },
      ],
      interactionType: "tap",
      question: { ar: "اضغط الناتج الصحيح لـ 2 + 3", en: "Tap the correct sum for 2 + 3" },
      answerOptions: [
        { ar: "4", en: "4" },
        { ar: "5", en: "5" },
        { ar: "6", en: "6" },
        { ar: "7", en: "7" },
      ],
      correctAnswer: 1,
      firstHint: { ar: "ثلاث قفزات من الرقم 2.", en: "Three jumps from 2." },
      secondExplanation: {
        ar: "2 ثم 3 ثم 4 ثم 5. الناتج 5.",
        en: "2 then 3 then 4 then 5. Answer 5.",
      },
      correctFeedback: { ar: "ممتاز! أنت تفهم القفزات.", en: "Excellent! You understand the jumps." },
      incorrectFeedback: { ar: "أعد العدّ ببطء.", en: "Count again slowly." },
      accessibilityText: { ar: "تمرين اثنين زائد ثلاثة", en: "Practice 2+3" },
      completionRule: "interaction",
      audio: {
        ar: "/interactive-lessons/g1-math/audio/ar/practice-2-plus-3.mp3",
        en: "/interactive-lessons/g1-math/audio/en/practice-2-plus-3.mp3",
      },
    },
    {
      sceneId: "guided-3-demo",
      sceneType: "guided",
      durationMs: 13000,
      learningGoal: { ar: "مثال ثالث 4+1", en: "Third example 4+1" },
      narration: {
        ar: "مثال ثالث: أربعة زائد واحد. نبدأ من 4، قفزة واحدة إلى 5. سهل وواضح.",
        en: "Third example: four plus one. Start at 4, one jump to 5. Simple and clear.",
      },
      captions: { ar: "4 → 5", en: "4 → 5" },
      board: "jumps",
      visualTimeline: [
        { atMs: 300, action: "show_line" },
        { atMs: 1000, action: "place_start", value: 4 },
        { atMs: 2800, action: "jump", from: 4, to: 5 },
        { atMs: 5000, action: "show_equation", value: "4 + 1 = 5" },
      ],
      interactionType: "none",
      correctAnswer: 0,
      accessibilityText: { ar: "عرض أربعة زائد واحد", en: "Demo 4+1" },
      completionRule: "auto",
      audio: {
        ar: "/interactive-lessons/g1-math/audio/ar/guided-3-demo.mp3",
        en: "/interactive-lessons/g1-math/audio/en/guided-3-demo.mp3",
      },
    },
    {
      sceneId: "practice-type",
      sceneType: "practice",
      durationMs: 8000,
      learningGoal: { ar: "اكتب الناتج", en: "Type the sum" },
      narration: {
        ar: "اكتب الناتج بنفسك: أربعة زائد واحد.",
        en: "Type the answer yourself: four plus one.",
      },
      captions: { ar: "4 + 1 = ؟", en: "4 + 1 = ?" },
      board: "equation",
      visualTimeline: [
        { atMs: 200, action: "show_line" },
        { atMs: 500, action: "show_equation", value: "4 + 1 = ?" },
      ],
      interactionType: "type",
      question: { ar: "اكتب ناتج 4 + 1", en: "Type the sum of 4 + 1" },
      correctAnswer: "5",
      firstHint: { ar: "قفزة واحدة فقط من 4.", en: "Only one jump from 4." },
      secondExplanation: { ar: "4 ثم قفزة إلى 5.", en: "4 then jump to 5." },
      correctFeedback: { ar: "صحيح تماماً!", en: "Exactly right!" },
      incorrectFeedback: { ar: "جرّب كتابة الرقم 5.", en: "Try writing the number 5." },
      accessibilityText: { ar: "اكتب إجابة أربعة زائد واحد", en: "Type answer for 4+1" },
      completionRule: "interaction",
      audio: {
        ar: "/interactive-lessons/g1-math/audio/ar/practice-type.mp3",
        en: "/interactive-lessons/g1-math/audio/en/practice-type.mp3",
      },
    },
    {
      sceneId: "arrange",
      sceneType: "practice",
      durationMs: 8000,
      learningGoal: { ar: "رتّب خطوات الجمع", en: "Order the steps" },
      narration: {
        ar: "اسحب البطاقات ورتّب خطوات الجمع بالترتيب الصحيح.",
        en: "Drag the cards and put the addition steps in the correct order.",
      },
      captions: { ar: "رتّب الخطوات", en: "Order the steps" },
      board: "equation",
      visualTimeline: [{ atMs: 200, action: "show_equation", value: "؟ → ؟ → ؟" }],
      interactionType: "drag",
      question: {
        ar: "اسحب لترتيب الخطوات",
        en: "Drag to order the steps",
      },
      answerOptions: [
        { ar: "ابدأ من العدد الأول", en: "Start at the first number" },
        { ar: "اقفز لليمين", en: "Jump to the right" },
        { ar: "اقرأ الناتج", en: "Read the sum" },
      ],
      correctAnswer: [0, 1, 2],
      firstHint: { ar: "نبدأ دائماً من العدد الأول.", en: "We always start from the first number." },
      secondExplanation: {
        ar: "الترتيب: ابدأ، اقفز، ثم اقرأ الناتج.",
        en: "Order: start, jump, then read the sum.",
      },
      correctFeedback: { ar: "ترتيب ممتاز!", en: "Perfect order!" },
      incorrectFeedback: { ar: "أعد ترتيب الخطوات.", en: "Reorder the steps." },
      accessibilityText: { ar: "ترتيب خطوات الجمع بالسحب", en: "Drag to arrange addition steps" },
      completionRule: "interaction",
      audio: {
        ar: "/interactive-lessons/g1-math/audio/ar/arrange.mp3",
        en: "/interactive-lessons/g1-math/audio/en/arrange.mp3",
      },
    },
    {
      sceneId: "match-sums",
      sceneType: "practice",
      durationMs: 9000,
      learningGoal: { ar: "طابق المعادلة بالناتج", en: "Match equation to sum" },
      narration: {
        ar: "طابق كل معادلة مع الناتج الصحيح.",
        en: "Match each equation with the correct sum.",
      },
      captions: { ar: "طابق المعادلات", en: "Match the equations" },
      board: "equation",
      visualTimeline: [{ atMs: 200, action: "show_equation", value: "؟ = ؟" }],
      interactionType: "match",
      question: { ar: "طابق المعادلة بالناتج", en: "Match each equation to its sum" },
      answerOptions: [
        { ar: "3 + 2", en: "3 + 2" },
        { ar: "5 + 1", en: "5 + 1" },
        { ar: "2 + 2", en: "2 + 2" },
      ],
      matchTargets: [
        { ar: "5", en: "5" },
        { ar: "6", en: "6" },
        { ar: "4", en: "4" },
      ],
      correctAnswer: [0, 1, 2],
      firstHint: {
        ar: "استخدم خط الأعداد في ذهنك لكل معادلة.",
        en: "Use the number line in your mind for each equation.",
      },
      secondExplanation: {
        ar: "3+2=5، و5+1=6، و2+2=4.",
        en: "3+2=5, 5+1=6, and 2+2=4.",
      },
      correctFeedback: { ar: "مطابقة رائعة!", en: "Great matching!" },
      incorrectFeedback: { ar: "تحقق من كل معادلة بهدوء.", en: "Check each equation calmly." },
      accessibilityText: { ar: "مطابقة معادلات الجمع", en: "Match addition equations" },
      completionRule: "interaction",
      audio: {
        ar: "/interactive-lessons/g1-math/audio/ar/match-sums.mp3",
        en: "/interactive-lessons/g1-math/audio/en/match-sums.mp3",
      },
    },
    {
      sceneId: "application",
      sceneType: "application",
      durationMs: 12000,
      learningGoal: { ar: "من واقع الحياة", en: "Real life" },
      narration: {
        ar: "في الملعب: معك 3 كرات، وأخذت كرتين. كم صارت؟ استخدم خط الأعداد في ذهنك.",
        en: "On the playground: you have 3 balls, then get 2 more. How many now? Use the number line in your mind.",
      },
      captions: { ar: "3 كرات + 2 = ؟", en: "3 balls + 2 = ?" },
      board: "objects",
      visualTimeline: [
        { atMs: 400, action: "show_objects", count: 3 },
        { atMs: 3500, action: "show_objects", count: 5 },
        { atMs: 6000, action: "show_equation", value: "3 + 2 = 5" },
      ],
      interactionType: "mcq",
      question: { ar: "3 كرات + 2 = ؟", en: "3 balls + 2 = ?" },
      answerOptions: [
        { ar: "4", en: "4" },
        { ar: "5", en: "5" },
        { ar: "6", en: "6" },
      ],
      correctAnswer: 1,
      firstHint: { ar: "نفس مسألة 3 + 2 التي تعلمناها.", en: "Same as the 3 + 2 we learned." },
      secondExplanation: { ar: "3 ثم قفزتان تصل إلى 5 كرات.", en: "3 then two jumps reach 5 balls." },
      correctFeedback: { ar: "رائع! الرياضيات في حياتنا.", en: "Awesome! Math is in our life." },
      incorrectFeedback: { ar: "تخيّل القفز على الخط.", en: "Imagine jumping on the line." },
      accessibilityText: { ar: "تطبيق حياتي على الجمع", en: "Real-life addition application" },
      completionRule: "interaction",
      audio: {
        ar: "/interactive-lessons/g1-math/audio/ar/application.mp3",
        en: "/interactive-lessons/g1-math/audio/en/application.mp3",
      },
    },
    {
      sceneId: "quiz-1",
      sceneType: "quiz",
      durationMs: 7000,
      learningGoal: { ar: "اختبار قصير 1", en: "Short quiz 1" },
      narration: { ar: "اختبار قصير: خمسة زائد واحد؟", en: "Quick quiz: five plus one?" },
      captions: { ar: "5 + 1 = ؟", en: "5 + 1 = ?" },
      board: "equation",
      visualTimeline: [{ atMs: 200, action: "show_equation", value: "5 + 1 = ?" }],
      interactionType: "mcq",
      question: { ar: "5 + 1 = ؟", en: "5 + 1 = ?" },
      answerOptions: [
        { ar: "5", en: "5" },
        { ar: "6", en: "6" },
        { ar: "7", en: "7" },
      ],
      correctAnswer: 1,
      firstHint: { ar: "من 5 قفزة واحدة.", en: "One jump from 5." },
      secondExplanation: { ar: "5 + 1 = 6.", en: "5 + 1 = 6." },
      correctFeedback: { ar: "صحيح!", en: "Correct!" },
      incorrectFeedback: { ar: "حاول مجدداً.", en: "Try again." },
      accessibilityText: { ar: "اختبار خمسة زائد واحد", en: "Quiz 5+1" },
      completionRule: "interaction",
      audio: {
        ar: "/interactive-lessons/g1-math/audio/ar/quiz-1.mp3",
        en: "/interactive-lessons/g1-math/audio/en/quiz-1.mp3",
      },
    },
    {
      sceneId: "quiz-2",
      sceneType: "quiz",
      durationMs: 7000,
      learningGoal: { ar: "اختبار قصير 2", en: "Short quiz 2" },
      narration: { ar: "آخر سؤال: واحد زائد أربعة؟", en: "Last question: one plus four?" },
      captions: { ar: "1 + 4 = ؟", en: "1 + 4 = ?" },
      board: "equation",
      visualTimeline: [{ atMs: 200, action: "show_equation", value: "1 + 4 = ?" }],
      interactionType: "draw",
      question: { ar: "اكتب ناتج 1 + 4 على السبورة", en: "Write the sum of 1 + 4 on the board" },
      correctAnswer: "5",
      firstHint: { ar: "ابدأ من 1 واقفز أربع مرات.", en: "Start at 1 and jump four times." },
      secondExplanation: { ar: "1→2→3→4→5.", en: "1→2→3→4→5." },
      correctFeedback: { ar: "أنت بطل الجمع!", en: "You are an addition champion!" },
      incorrectFeedback: { ar: "عدّ القفزات واحدة واحدة.", en: "Count the jumps one by one." },
      accessibilityText: { ar: "اكتب إجابة واحد زائد أربعة", en: "Write answer for 1+4" },
      completionRule: "interaction",
      audio: {
        ar: "/interactive-lessons/g1-math/audio/ar/quiz-2.mp3",
        en: "/interactive-lessons/g1-math/audio/en/quiz-2.mp3",
      },
    },
    {
      sceneId: "result",
      sceneType: "result",
      durationMs: 10000,
      learningGoal: { ar: "نتيجة الدرس", en: "Lesson result" },
      narration: {
        ar: "أحسنت! أنهيت درس الجمع بخط الأعداد. راجع أي سؤال أخطأت فيه، ثم انتقل للدرس التالي عندما تكون جاهزاً.",
        en: "Well done! You finished addition on the number line. Review any missed questions, then continue when ready.",
      },
      captions: { ar: "أحسنت · تحقق من إتقانك", en: "Well done · check your mastery" },
      board: "celebrate",
      visualTimeline: [
        { atMs: 300, action: "celebrate" },
        { atMs: 800, action: "show_equation", value: "★" },
      ],
      interactionType: "none",
      correctAnswer: 0,
      accessibilityText: { ar: "شاشة النتيجة والتشجيع", en: "Results and encouragement" },
      completionRule: "continue",
      audio: {
        ar: "/interactive-lessons/g1-math/audio/ar/result.mp3",
        en: "/interactive-lessons/g1-math/audio/en/result.mp3",
      },
    },
  ],
};
