'use client';
import {useMemo,useState} from 'react';
import {InnerNav} from '../components';

const profiles={
  'الأردن':{stages:['رياض الأطفال','التعليم الأساسي: الصف 1–10','التعليم الثانوي: الصف 11–12','التوجيهي أو مسارات دولية'],systems:['المنهاج الوطني الأردني','American Diploma','Cambridge IGCSE / A Level','IB','BTEC'],authority:'وزارة التربية والتعليم الأردنية'},
  'الإمارات العربية المتحدة':{stages:['رياض الأطفال','الحلقة الأولى','الحلقة الثانية','الحلقة الثالثة','التعليم العالي'],systems:['منهاج وزارة التربية الإماراتية','American Curriculum','British Curriculum','IB','CBSE'],authority:'وزارة التربية والتعليم الإماراتية'},
  'مصر':{stages:['رياض الأطفال','الابتدائي','الإعدادي','الثانوي العام أو الفني','التعليم العالي'],systems:['الثانوية العامة المصرية','American Diploma','IGCSE','IB','STEM Schools','EST / ACT للقبول'],authority:'وزارة التربية والتعليم والتعليم الفني'},
  'السعودية':{stages:['رياض الأطفال','الابتدائي','المتوسط','الثانوي ومساراته','التعليم العالي'],systems:['المنهج السعودي','المسارات الثانوية','American Curriculum','British Curriculum','IB'],authority:'وزارة التعليم السعودية'},
  'الولايات المتحدة':{stages:['Elementary School','Middle School','High School','College / University'],systems:['State Standards','US High School Diploma','AP','IB','Dual Enrollment'],authority:'State education agencies'},
  'المملكة المتحدة':{stages:['Early Years','Primary','Secondary','Sixth Form / College','Higher Education'],systems:['National Curriculum','GCSE','A Level','BTEC','Scottish Curriculum','IB'],authority:'UK education authorities'},
  'كندا':{stages:['Elementary','Secondary','College / University'],systems:['Provincial Curriculum','OSSD and provincial diplomas','AP','IB','French-language systems'],authority:'Provincial and territorial ministries'},
  'تركيا':{stages:['Okul öncesi','İlkokul','Ortaokul','Lise','Yükseköğretim'],systems:['المنهج الوطني التركي','Anatolian High School','IB','Cambridge International'],authority:'Millî Eğitim Bakanlığı'},
  'الهند':{stages:['Pre-primary','Primary','Upper Primary','Secondary','Senior Secondary','Higher Education'],systems:['CBSE','CISCE / ISC','State Boards','IB','Cambridge'],authority:'Ministry and national/state boards'},
  'أستراليا':{stages:['Foundation','Primary','Secondary','Senior Secondary','Tertiary'],systems:['Australian Curriculum','State senior certificates','ATAR','IB'],authority:'Australian and state education authorities'},
  'فرنسا':{stages:['École maternelle','École élémentaire','Collège','Lycée','Enseignement supérieur'],systems:['Programme national','Baccalauréat général','Baccalauréat technologique','Baccalauréat professionnel','IB'],authority:"Ministère de l'Éducation nationale"},
  'ألمانيا':{stages:['Kindergarten','Grundschule','Secondary pathways','Vocational or upper secondary','Higher Education'],systems:['State curricula','Gymnasium / Abitur','Realschule','Hauptschule','Berufsschule','IB'],authority:'Länder education ministries'},
  'الجزائر':{stages:['تحضيري','ابتدائي','متوسط','ثانوي','تعليم عالٍ'],systems:['المنهاج الوطني الجزائري','البكالوريا الجزائرية','البكالوريا الفرنسية','Cambridge International'],authority:'وزارة التربية الوطنية'},
  'المغرب':{stages:['أولي','ابتدائي','إعدادي','ثانوي تأهيلي','تعليم عالٍ'],systems:['المنهاج المغربي','البكالوريا المغربية','المسار الدولي','البكالوريا الفرنسية','IB'],authority:'وزارة التربية الوطنية'},
  'باكستان':{stages:['Primary','Middle','Secondary','Higher Secondary','Higher Education'],systems:['Matric / Intermediate','Cambridge O Level / A Level','IB'],authority:'Federal and provincial authorities'},
  'سنغافورة':{stages:['Primary','Secondary','Post-secondary','Higher Education'],systems:['Singapore Curriculum','Singapore-Cambridge','Integrated Programme','IB'],authority:'Ministry of Education Singapore'}
};
const iso='AD AE AF AG AI AL AM AO AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BR BS BT BW BY BZ CA CD CF CG CH CI CK CL CM CN CO CR CU CV CY CZ DE DJ DK DM DO DZ EC EE EG ER ES ET FI FJ FM FR GA GB GD GE GH GI GL GM GN GQ GR GT GW GY HK HN HR HT HU ID IE IL IN IQ IR IS IT JM JO JP KE KG KH KI KM KN KP KR KW KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MG MH MK ML MM MN MO MR MT MU MV MW MX MY MZ NA NE NG NI NL NO NP NR NZ OM PA PE PG PH PK PL PR PS PT PW PY QA RO RS RU RW SA SB SC SD SE SG SI SK SL SM SN SO SR SS ST SV SY SZ TD TG TH TJ TL TM TN TO TR TT TV TW TZ UA UG US UY UZ VA VC VE VN VU WS YE ZA ZM ZW'.split(' ');
const regionNames=new Intl.DisplayNames(['ar'],{type:'region'});
const countries=iso.map(code=>regionNames.of(code)).filter(Boolean).sort((a,b)=>a.localeCompare(b,'ar'));

export default function WorldPage(){const [country,setCountry]=useState('الأردن');const profile=profiles[country];const fallback=useMemo(()=>({stages:['الطفولة المبكرة','التعليم الابتدائي','التعليم الثانوي','التعليم ما بعد الثانوي','التعليم العالي'],systems:[`النظام الوطني في ${country}`,'برامج دولية عند توفرها','مسارات مهنية وتقنية'],authority:'الجهة الوطنية المختصة — يلزم التحقق من الرابط الرسمي'}),[country]);const p=profile||fallback;return <div className="os-page phase11-legacy-page"><InnerNav active="world"/><main className="os-page-content world-page"><header className="world-hero"><div><span>GLOBAL EDUCATION ATLAS</span><h1>أنظمة التعليم لجميع دول العالم</h1><p>طبقة موحدة تربط اسم الدولة بمراحلها وأنظمتها المحلية والدولية، ثم بالصف والمادة والقبول الجامعي. تعرض المنصة حالة التحقق ولا تدّعي دقة غير موثقة.</p></div><div><b>201</b><small>خريطة دولة متاحة لدى UNESCO ISCED</small></div></header><section className="world-picker"><label>اختر الدولة<select value={country} onChange={e=>setCountry(e.target.value)}>{countries.map(x=><option key={x}>{x}</option>)}</select></label><div className={profile?'world-verified':'world-pending'}>{profile?'✓ ملف إطلاق مُراجع':'! ملف عام — بانتظار إدخال الخريطة الوطنية'}</div></section><section className="world-grid"><article><small>المراحل التعليمية</small><h2>{country}</h2><ol>{p.stages.map((x,i)=><li key={x}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span></li>)}</ol></article><article><small>الأنظمة والمسارات</small><h2>خيارات الدراسة</h2><div className="world-chips">{p.systems.map(x=><span key={x}>{x}</span>)}</div><h3>الجهة المرجعية</h3><p>{p.authority}</p></article><aside><small>المصدر العالمي</small><h2>تحقق قبل القرار</h2><p>تستخدم SUCCESS OS تصنيف ISCED للمقارنة، ثم تحيل المستخدم إلى خرائط الدولة والجهة الوطنية. بيانات القبول النهائية تؤخذ من الجامعة نفسها.</p><a href="https://www.uis.unesco.org/en/methods-and-tools/isced/mapping-and-diagrams" target="_blank" rel="noreferrer">خرائط UNESCO ISCED ↗</a><a href="https://www.uis.unesco.org/en/data/sdg4-country-profiles" target="_blank" rel="noreferrer">ملفات SDG 4 للدول ↗</a><a href="/admissions">انتقل إلى الجامعات والكليات ←</a></aside></section></main></div>}
