'use client';
import {useEffect,useMemo,useState} from 'react';import {Sidebar,Topbar} from '../components';import {starterCurricula} from '../data/starter-curricula';
const jordanGrades=Array.from({length:12},(_,i)=>`الصف ${i+1}`);
export default function StudentContentLibrary(){
 const [rows,setRows]=useState([]),[selected,setSelected]=useState(null),[mode,setMode]=useState('jordan'),[q,setQ]=useState(''),[grade,setGrade]=useState('الصف 1'),[catalog,setCatalog]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{try{setRows(JSON.parse(localStorage.getItem('success-os-generated-content')||'[]'))}catch{}},[]);
 useEffect(()=>{if(mode!=='jordan')return;let live=true;setLoading(true);setError('');fetch('/api/jordan-curriculum',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'scan-grade',grade})}).then(r=>r.json().then(data=>({ok:r.ok,data}))).then(({ok,data})=>{if(!live)return;if(!ok)throw new Error(data.error||'تعذر تحميل الكتب');setCatalog(data)}).catch(e=>live&&setError(e.message)).finally(()=>live&&setLoading(false));return()=>{live=false}},[mode,grade]);
 const visible=useMemo(()=>{const source=mode==='base'?starterCurricula:rows;return source.filter(x=>!q||`${x.title} ${x.subject||''} ${x.system||''}`.toLowerCase().includes(q.toLowerCase()))},[mode,rows,q]);
 const jordanResources=useMemo(()=>(catalog?.resources||[]).filter(x=>!q||`${x.subject} ${x.type} ${x.semester}`.includes(q)),[catalog,q]);
 const remove=id=>{const next=rows.filter(x=>x.id!==id);setRows(next);localStorage.setItem('success-os-generated-content',JSON.stringify(next))};
 return <div className="os-shell phase11-private-shell"><Sidebar active="student-portal"/><main className="os-main"><Topbar/><div className="os-content generated-library-page"><header><div><small>SUCCESS OS LEARNING LIBRARY</small><h1>مكتبة الطالب</h1><p>كتب الأردن الرسمية من مصدرها، وكتب SUCCESS OS الأصلية، ومحتواك المحفوظ في مكان واحد.</p></div><a href="/study-content-generator">＋ إنشاء محتوى جديد</a></header><section className="library-mode-bar"><button className={mode==='jordan'?'active':''} onClick={()=>setMode('jordan')}>كتب الأردن الرسمية</button><button className={mode==='mine'?'active':''} onClick={()=>setMode('mine')}>مكتبتي ({rows.length})</button><button className={mode==='base'?'active':''} onClick={()=>setMode('base')}>كتب SUCCESS OS ({starterCurricula.length})</button><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث عن مادة أو كتاب"/></section>
 {mode==='jordan'?<><section className="library-mode-bar"><label>اختر الصف <select value={grade} onChange={e=>setGrade(e.target.value)}>{jordanGrades.map(item=><option key={item}>{item}</option>)}</select></label><a href={catalog?.sourceUrl||'https://www.nccd.gov.jo/Ar/Pages/textbooks'} target="_blank" rel="noreferrer">المصدر الرسمي للمركز الوطني ↗</a></section>{loading?<section className="generated-library-empty"><span>◌</span><h2>جاري جلب كتب {grade}</h2><p>يتم الاتصال بالمصدر الرسمي مباشرة.</p></section>:error?<section className="generated-library-empty"><span>!</span><h2>تعذر جلب الكتب الآن</h2><p>{error}</p><a href={catalog?.sourceUrl||'https://www.nccd.gov.jo/Ar/Pages/textbooks'} target="_blank" rel="noreferrer">فتح المصدر الرسمي</a></section>:jordanResources.length?<section className="generated-library-grid">{jordanResources.map((book,index)=><article key={`${book.url}-${index}`}><div><span>▦</span><small>{book.grade} • {book.semester}</small></div><h2>{book.subject}</h2><p>{book.type}</p><section><b>المنهاج الوطني الأردني</b><em>مصدر رسمي</em><i>✓ موثق المصدر</i></section><footer><a href={book.url} target="_blank" rel="noreferrer">فتح الكتاب الرسمي</a></footer></article>)}</section>:<section className="generated-library-empty"><span>!</span><h2>لم تظهر روابط الكتب تلقائياً</h2><p>افتح صفحة الصف الرسمية الآن، بينما نراجع بنية الصفحة.</p><a href={catalog?.sourceUrl||'https://www.nccd.gov.jo/Ar/Pages/textbooks'} target="_blank" rel="noreferrer">فتح كتب {grade}</a></section>}<p>هذه الموارد منشورة من المركز الوطني وتبقى حقوقها لأصحابها. كتب SUCCESS OS الأصلية تُكتب من الصفر وتظهر في تبويب مستقل بعد اكتمال المراجعة.</p></>:visible.length?<section className="generated-library-grid">{visible.map(x=><article key={x.id}><div><span>{x.track==='university'?'⚛':'▦'}</span><small>{x.id} • {x.created}</small></div><h2>{x.title}</h2><p>{x.context}</p><section><b>{x.units?.length?`${x.units.length} وحدات`:`${x.questions?.length||0} أسئلة`}</b><em>{x.mode==='platform-seed'?`إصدار ${x.version}`:x.mode==='openai'?'OpenAI':'مسودة احتياطية'}</em><i>⬡ محمي</i></section><footer><button onClick={()=>setSelected(x)}>فتح المحتوى</button>{x.mode==='platform-seed'?<a href={`/subject-learning-hub?system=${encodeURIComponent(x.system)}&subject=${encodeURIComponent(x.subject)}&view=book`}>تخصيص وتحديث</a>:<button onClick={()=>remove(x.id)}>حذف</button>}</footer></article>)}</section>:<section className="generated-library-empty"><span>✦</span><h2>لا توجد نتيجة مطابقة</h2><p>غيّر البحث أو افتح كتب الأردن الرسمية.</p></section>}
 {selected&&<div className="library-preview-modal" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><div><button onClick={()=>setSelected(null)}>×</button><small>{selected.context}</small><h2>{selected.title}</h2>{selected.summary&&<p>{selected.summary}</p>}{selected.units?.length>0&&<><h3>الفهرس</h3>{selected.units.map((u,i)=><section key={u.title}><b>{i+1}. {u.title}</b><p>{u.duration} • {u.status}</p></section>)}</>}{selected.reviewStatus&&<p><b>حالة المراجعة:</b> {selected.reviewStatus}</p>}</div></div>}
 </div></main></div>}
