'use client';
import {useEffect,useMemo,useState} from 'react';
import {InnerNav} from '../components';

const types={teacher:['♙','المعلمون','/teachers'],center:['▦','المراكز التعليمية','/partner-search?portal=center'],school:['⌂','المدارس','/school-finder'],university:['🎓','الجامعات','/admissions'],college:['◫','الكليات','/admissions'],employer:['↗','شركات التوظيف','/jobs']};
const partners={
 teacher:[{name:'Success Teacher Network',country:'الأردن',city:'عمّان',mode:'هجين',field:'AP • EST • IGCSE • A Level',verified:true},{name:'Global Online Tutors',country:'عالمي',city:'أونلاين',mode:'أونلاين',field:'IB • Cambridge • American',verified:false}],
 center:[{name:'Success 4 Sure Academy',country:'الأردن',city:'عمّان',mode:'هجين',field:'دورات • حصص • امتحانات دولية',verified:true},{name:'International Learning Center',country:'عالمي',city:'أونلاين',mode:'أونلاين',field:'لغات • STEM • مهارات',verified:false},{name:'STEM Learning Hub — نموذج',country:'الإمارات',city:'دبي',mode:'حضوري',field:'علوم • برمجة • روبوتات',verified:false}],
 school:[{name:'مدرسة دولية أمريكية — نموذج',country:'الأردن',city:'عمّان',mode:'حضوري',field:'American Curriculum',verified:false},{name:'مدرسة IB — نموذج',country:'الإمارات',city:'دبي',mode:'حضوري',field:'IB Continuum',verified:false},{name:'مدرسة كامبردج أونلاين — نموذج',country:'عالمي',city:'أونلاين',mode:'أونلاين',field:'Cambridge International',verified:false}],
 university:[{name:'جامعة معترف بها — نتيجة نموذجية',country:'الأردن',city:'عمّان',mode:'حضوري',field:'بكالوريوس • ماجستير • دكتوراه',verified:true},{name:'جامعة أونلاين — نتيجة نموذجية',country:'عالمي',city:'أونلاين',mode:'أونلاين',field:'برامج تمنح درجة',verified:false}],
 college:[{name:'كلية تمنح درجة — نتيجة نموذجية',country:'الأردن',city:'عمّان',mode:'هجين',field:'دبلوم • بكالوريوس',verified:false},{name:'كلية تقنية — نتيجة نموذجية',country:'ألمانيا',city:'برلين',mode:'حضوري',field:'تطبيقية • مهنية',verified:false}],
 employer:[{name:'شركة تعليم وتقنية — نموذج',country:'الأردن',city:'عمّان',mode:'هجين',field:'تعليم • محتوى • هندسة',verified:false},{name:'جهة توظيف دولية — نموذج',country:'عالمي',city:'عن بعد',mode:'أونلاين',field:'وظائف عالمية',verified:false},{name:'شركة تعليمية — نموذج',country:'الإمارات',city:'دبي',mode:'حضوري',field:'تعليم • إدارة • تسويق',verified:false}]
};
const initial={country:'الكل',city:'الكل',mode:'الكل',verification:'الكل',query:''};

export default function PartnerSearch(){
 const [type,setType]=useState('teacher'),[filters,setFilters]=useState(initial);
 useEffect(()=>{const p=new URLSearchParams(window.location.search).get('portal');if(types[p])setType(p)},[]);
 const source=partners[type],countries=['الكل',...new Set(source.map(x=>x.country))],cities=['الكل',...new Set(source.filter(x=>filters.country==='الكل'||x.country===filters.country).map(x=>x.city))],modes=['الكل',...new Set(source.map(x=>x.mode))];
 const rows=useMemo(()=>source.filter(x=>(filters.country==='الكل'||x.country===filters.country)&&(filters.city==='الكل'||x.city===filters.city)&&(filters.mode==='الكل'||x.mode===filters.mode)&&(filters.verification==='الكل'||(filters.verification==='موثق'?x.verified:!x.verified))&&(!filters.query||`${x.name} ${x.field} ${x.country} ${x.city}`.toLowerCase().includes(filters.query.toLowerCase()))),[source,filters]);
 const update=(key,value)=>setFilters(f=>({...f,[key]:value,...(key==='country'?{city:'الكل'}:{})}));const reset=()=>setFilters(initial);const [icon,label,advanced]=types[type];const serviceLabel=type==='employer'?'طريقة العمل':type==='school'||type==='university'||type==='college'?'نمط الدراسة':'طريقة الخدمة';
 return <div className="os-page phase11-legacy-page"><InnerNav active="access"/><main className="os-page-content partner-search-page">
  <header className="partner-search-hero"><div><small>SEARCH THE SUCCESS NETWORK</small><h1>ابحث عن {label}</h1><p>فلترة فعلية حسب الموقع وطريقة الخدمة وحالة التحقق والاسم أو التخصص، ثم انتقال إلى الدليل المتخصص للمقارنة والتقديم.</p></div><a href={`/join-us?role=${type}`}>＋ انضم إلى {label}</a></header>
  <nav className="partner-type-tabs">{Object.entries(types).map(([id,[i,l]])=><button className={id===type?'active':''} onClick={()=>{setType(id);setFilters(initial)}} key={id}><span>{i}</span>{l}</button>)}</nav>
  <section className="directory-filter partner-search-filter"><header><div><small>FILTER RESULTS</small><h2>خصص نتائج البحث</h2></div><button type="button" onClick={reset}>مسح الفلاتر</button></header><div><label>الدولة<select value={filters.country} onChange={e=>update('country',e.target.value)}>{countries.map(x=><option key={x}>{x}</option>)}</select></label><label>المدينة<select value={filters.city} onChange={e=>update('city',e.target.value)}>{cities.map(x=><option key={x}>{x}</option>)}</select></label><label>{serviceLabel}<select value={filters.mode} onChange={e=>update('mode',e.target.value)}>{modes.map(x=><option key={x}>{x}</option>)}</select></label><label>حالة التحقق<select value={filters.verification} onChange={e=>update('verification',e.target.value)}><option>الكل</option><option>موثق</option><option>قيد التحقق</option></select></label><label className="filter-search">الاسم أو التخصص<input value={filters.query} onChange={e=>update('query',e.target.value)} placeholder={`ابحث في ${label}`}/></label></div><footer><b>{rows.length} نتائج</b><span>طريقة التصنيف تتغير تلقائياً حسب البوابة المختارة</span></footer></section>
  <div className="partner-result-note"><span>◎</span><p>القائمة تتغير حسب الدولة وحالة الاعتماد. تحقق دائماً من الجهة الرسمية قبل الدفع أو التسجيل أو مشاركة البيانات.</p></div>
  {rows.length?<section className="partner-result-grid">{rows.map(x=><article key={x.name}><header><span>{icon}</span><div><small>{x.country} • {x.city} • {x.mode}</small><h2>{x.name}</h2></div><b className={x.verified?'verified':'pending'}>{x.verified?'موثق':'قيد التحقق'}</b></header><p>{x.field}</p><div><span>✓ ملف تعريفي</span><span>✓ طلب تواصل</span><span>✓ حالة تحقق واضحة</span></div><footer><a href={advanced}>عرض الدليل المتخصص</a><a href={`/join-us?role=${type}`}>انضم كشريك</a></footer></article>)}</section>:<section className="directory-empty"><span>⌕</span><h2>لا توجد نتائج مطابقة</h2><p>جرّب توسيع الدولة أو طريقة الخدمة أو مسح بعض الفلاتر.</p><button onClick={reset}>مسح الفلاتر</button></section>}
 </main></div>
}
